In [1]:
import pandas as pd
from Bio.PDB import PDBParser, PDBIO, Select
from esm.utils.structure.protein_chain import ProteinChain

df = pd.read_csv('/home/sareeves/PSLMs/data/domainome1/SupplementaryTable5.txt', sep='\t')
df = df.loc[~df['uniprot_ID_mutation'].str.endswith('*')]
df

,domain_ID,uniprot_ID,uniprot_ID_mutation,aa_seq,fitness,fitness_sigma,scaled_fitness,scaled_fitness_sigma,ESM1v_domain,RaSP,...,EVE,Tranception,EVE_domain,rsasa,thermoMPNN,AlphaMissense,ESM1v_full-length,Organism,Gene Names (primary),Gene Names (synonym)
1,A0A2R8Y422_PF00240_2,A0A2R8Y422,A0A2R8Y422_A28C,QIFVKTLMGKTITLEVELSDTIDNVKCKIQDKEGIPPDQQRLIFAG...,0.091262,0.003764,0.025738,0.052712,-9.862297,0.944872,...,NaN,NaN,4.980072,41.3,-0.120494,0.3340,NaN,Homo sapiens (Human),NaN,NaN
2,A0A2R8Y422_PF00240_2,A0A2R8Y422,A0A2R8Y422_A28D,QIFVKTLMGKTITLEVELSDTIDNVKDKIQDKEGIPPDQQRLIFAG...,0.097388,0.003962,0.111544,0.055491,-8.525545,0.344768,...,NaN,NaN,3.766518,41.3,0.842978,0.2790,NaN,Homo sapiens (Human),NaN,NaN
3,A0A2R8Y422_PF00240_2,A0A2R8Y422,A0A2R8Y422_A28E,QIFVKTLMGKTITLEVELSDTIDNVKEKIQDKEGIPPDQQRLIFAG...,0.110153,0.007189,0.290325,0.100693,-7.011676,-0.044519,...,NaN,NaN,2.854782,41.3,0.355797,0.2014,NaN,Homo sapiens (Human),NaN,NaN
4,A0A2R8Y422_PF00240_2,A0A2R8Y422,A0A2R8Y422_A28F,QIFVKTLMGKTITLEVELSDTIDNVKFKIQDKEGIPPDQQRLIFAG...,0.089583,0.003577,0.002225,0.050106,-10.680157,-0.423373,...,NaN,NaN,5.208206,41.3,0.118878,0.3648,NaN,Homo sapiens (Human),NaN,NaN
5,A0A2R8Y422_PF00240_2,A0A2R8Y422,A0A2R8Y422_A28G,QIFVKTLMGKTITLEVELSDTIDNVKGKIQDKEGIPPDQQRLIFAG...,0.087045,0.003294,-0.033329,0.046134,-7.925185,0.662229,...,NaN,NaN,4.270241,41.3,0.776435,0.1135,NaN,Homo sapiens (Human),NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
607076,Q9Y6V0_PF05715_1058,Q9Y6V0,Q9Y6V0_W1104S,TCPLCKTELNIGSKDPPNFNTCTECKNQVCNLCGFNPTPHLTEIQE...,0.105455,0.012201,-0.029589,0.137867,-5.345161,5.397289,...,NaN,NaN,8.343338,11.8,2.117514,0.9588,-12.64865,Homo sapiens (Human),PCLO,ACZ KIAA0559
607077,Q9Y6V0_PF05715_1058,Q9Y6V0,Q9Y6V0_W1104T,TCPLCKTELNIGSKDPPNFNTCTECKNQVCNLCGFNPTPHLTEIQE...,0.090854,0.015305,-0.194564,0.172938,-5.214868,4.558003,...,NaN,NaN,9.494637,11.8,1.988062,0.9647,-14.00641,Homo sapiens (Human),PCLO,ACZ KIAA0559
607078,Q9Y6V0_PF05715_1058,Q9Y6V0,Q9Y6V0_W1104V,TCPLCKTELNIGSKDPPNFNTCTECKNQVCNLCGFNPTPHLTEIQE...,0.115816,0.010449,0.087485,0.118070,-4.870904,3.148088,...,NaN,NaN,8.973549,11.8,1.270481,0.9512,-13.55418,Homo sapiens (Human),PCLO,ACZ KIAA0559
607079,Q9Y6V0_PF05715_1058,Q9Y6V0,Q9Y6V0_W1104Y,TCPLCKTELNIGSKDPPNFNTCTECKNQVCNLCGFNPTPHLTEIQE...,0.064475,0.022245,-0.492635,0.251357,-4.390252,1.411740,...,NaN,NaN,8.418221,11.8,0.628391,0.8258,-11.89384,Homo sapiens (Human),PCLO,ACZ KIAA0559
607080,Q9Y6V0_PF05715_1058,Q9Y6V0,Q9Y6V0_NANANA,TCPLCKTELNIGSKDPPNFNTCTECKNQVCNLCGFNPTPHLTEIQE...,0.108073,0.004972,0.000000,0.056184,NaN,0.065591,...,NaN,NaN,NaN,78.0,NaN,NaN,NaN,Homo sapiens (Human),PCLO,ACZ KIAA0559

In [2]:
len(df['domain_ID'].unique())

522

In [3]:
def align_sequences(seq1, seq2, max_mismatches=1):
    """
    Find the largest aligned region between seq1 and seq2 (seq2 is a subset of seq1),
    allowing for gaps only at the ends of seq1.

    Args:
        seq1 (str): The longer sequence.
        seq2 (str): The shorter sequence (subset of seq1).
        max_mismatches (int): Maximum allowed mismatches in the alignment.

    Returns:
        Tuple[str, str, int, int]: Aligned seq1, aligned seq2, start index, end index.
    """
    best_start = -1
    best_end = -1
    best_mismatches = float('inf')
    best_aligned_seq1 = ""
    best_aligned_seq2 = ""

    for start in range(len(seq1) - len(seq2) + 1):
        # Extract the region of seq1 to compare with seq2
        subseq1 = seq1[start:start + len(seq2)]

        # Count mismatches
        mismatches = sum(1 for a, b in zip(subseq1, seq2) if a != b)

        # Update best alignment if mismatches are within limit and alignment is better
        if mismatches <= max_mismatches and (best_end - best_start) < (start + len(seq2) - start):
            best_start = start
            best_end = start + len(seq2)
            best_mismatches = mismatches
            best_aligned_seq1 = subseq1
            best_aligned_seq2 = seq2

    # Add gaps to the ends of seq1
    aligned_seq1 = ("-" * best_start) + best_aligned_seq1 + ("-" * (len(seq1) - best_end))
    aligned_seq2 = (" " * best_start) + best_aligned_seq2 + (" " * (len(seq1) - best_end))

    return aligned_seq1, aligned_seq2, best_start, best_end

In [4]:
import requests
import os
import glob
from tqdm.notebook import tqdm

def assert_diff_by_one(str1, str2):
    assert len(str1) == len(str2), "Strings are not of same length"
    diff_count = 0
    for i in range(min(len(str1), len(str2))):
        if str1[i] != str2[i]:
            diff_count += 1
    assert diff_count == 1, f"Strings are not different by exactly one character\n{str1}\n{str2}"

def get_alphafold_structure(uniprot_id, output_file):
    base_url = f"https://alphafold.ebi.ac.uk/files/AF-{uniprot_id}-F1-model_v4.pdb"
    
    response = requests.get(base_url)
    if response.status_code == 200:
        with open(output_file, 'w') as file:
            file.write(response.text)
        print(f"AlphaFold structure for {uniprot_id} saved to {output_file}")
    else:
        print(f"Structure for UniProt ID {uniprot_id} not found. Status code: {response.status_code}")

class ResidueRangeSelect(Select):
    """Custom selector to retain residues within a specific range."""
    def __init__(self, start_residue, end_residue, chain_id=None):
        self.start_residue = start_residue
        self.end_residue = end_residue
        self.chain_id = chain_id  # Optional: specify chain if needed

    def accept_residue(self, residue):
        # Get residue ID
        res_id = residue.get_id()[1]  # Residue number
        if self.chain_id is None or residue.get_full_id()[2] == self.chain_id:
            return self.start_residue <= res_id <= self.end_residue
        return False

def truncate_pdb(input_pdb, output_pdb, start_residue, end_residue, chain_id=None):
    """Truncate a PDB file to retain only residues in the specified range."""
    parser = PDBParser(QUIET=True)  # Suppress warnings
    structure = parser.get_structure("protein", input_pdb)

    # Use the custom selector to filter residues
    io = PDBIO()
    io.set_structure(structure)
    selector = ResidueRangeSelect(start_residue, end_residue, chain_id)
    io.save(output_pdb, selector)
    print(f"Truncated PDB saved to {output_pdb}")

failed_assertions = []
for (domain_id, uniprot_id), group in tqdm(df.groupby(['domain_ID', 'uniprot_ID'])):
    print(domain_id)
    subseq = group['aa_seq'].head(1).item()
    print(subseq)

    file = f"/home/sareeves/PSLMs/data/domainome1/alphafold_structures/{uniprot_id}.pdb"
    if not os.path.exists(file):
        get_alphafold_structure(uniprot_id, file)

    try:
        wt_prot = ProteinChain.from_pdb(file)
    except ValueError as e:
        print(e)
        print(f'Issue with loading {file}')
        continue
    except FileNotFoundError as e:
        print(e)
        print(f'No file for {file}') 
        continue     

    full_seq = wt_prot.sequence
    aligned_seq1, aligned_seq2, start, end = align_sequences(full_seq, subseq, max_mismatches=1)
    start += 1
    #print("Aligned seq1:", aligned_seq1)
    #print("Aligned seq2:", aligned_seq2)
    #print(f"Aligned region starts at {start}, ends at {end}")

    truncated_file = file.replace('.pdb', f'_{start}-{end}.pdb')
    truncate_pdb(file, truncated_file, start, end)
    trunc_prot = ProteinChain.from_pdb(truncated_file)

    #print(trunc_prot.sequence)
    assert_diff_by_one(subseq, trunc_prot.sequence)
    #print(subseq)
    #print(trunc_prot.sequence)

    df.loc[(df['domain_ID']==domain_id), 'pdb_file'] = truncated_file
    for idx, row in group.iterrows():
        wt = row['uniprot_ID_mutation'].split('_')[-1][0]
        try:
            pos = int(row['uniprot_ID_mutation'].split('_')[-1][1:-1])
        except:
            continue
        pos -= start
        mut = row['uniprot_ID_mutation'].split('_')[-1][-1]

        try:
            assert trunc_prot.sequence[pos] == wt
            assert row['aa_seq'][pos] == mut
        except:
            failed_assertions.append((domain_id, wt, pos, mut))
            print(domain_id, wt, pos, mut)
            print(trunc_prot.sequence)
            print(row['aa_seq'])
            continue
        df.at[idx, 'wt_seq'] = trunc_prot.sequence
        df.at[idx, 'wild_type'] = wt
        df.at[idx, 'position'] = pos+1
        df.at[idx, 'mutation'] = mut
        df.at[idx, 'uniprot_seq'] = full_seq
        df.at[idx, 'offset_up'] = -start+1

df.to_csv('../data/domainome1/domainome_mapped.csv')

  0%|          | 0/522 [00:00<?, ?it/s]

A0A2R8Y422_PF00240_2
QIFVKTLMGKTITLEVELSDTIDNVKCKIQDKEGIPPDQQRLIFAGKQLEDGRTLSDYNIQKESTLHLVL
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/A0A2R8Y422_2-71.pdb
A0PJY2_PF00096_289
VCKVCGKGFRQCSTLCRHKIIH
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/A0PJY2_289-310.pdb
A1X283_PF00018_155
EQYVVVANYQKQESSEISLSVGQVVDIIEKNESGWWFVSTCEEQGWVPATCLEGQ
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/A1X283_155-209.pdb
A1X283_PF00018_222
EEEKYTVIYPYTCRDQDEMNLERGAVVEVIQKNLEGWWKIRYQGKEGWAPASYLKKNSG
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/A1X283_222-280.pdb
A2RRE5_PF01846_267
SQQIATAKDKYEWLVSRIVKNHNENWLSVSRKMQCSPEYQDYVYLEGTQKAKKLFLQHIHRLK
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/A2RRE5_267-329.pdb
A6NK59_PF07525_532
RSLKHLCRLKIRKCMGRLHLRCPVFMSFLPLPNRLKCYVLY
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/A6NK59_532-572.pdb
EEHEE-rd3-0037_rockdoms_1
TTIKVNGQEYTVPLSPEQCAKAAKKRWPDYEVQIHGNTVKVTR
Structure for UniProt ID EEHEE-rd3-0037 not found. Status code: 404
[Errno 2] No such file or directory: '/home/sareeves/PSLMs/data/domainome1/alphafold_structures/EEHEE-rd3-0037.pdb'
No file for /home/sareeves/PSLMs/data/domainome1/alphafold_structures/EEHEE-rd3-0037.pdb
EHEE-rd1-0882_rockdoms_1
QETIEVEDEEECRRVAKELRKKGYEVKIERRGNKWHVHRT
Structure for UniProt ID EHEE-rd1-0882 not found. Status code: 404
[Errno 2] No such file or directory: '/home/sareeves/PSLMs/data/domainome1/alphafold_structures/EHEE-rd1-0882.pdb'
No file for /home/sareeves/PSLMs/data/domainome1/alphafold_structures/EHEE-rd1-0882.pdb
HHH-rd1-0142_rockdoms_1
RKWEEIAERLREEFNINPEECREAVEKAGGNEEEARRIVKKRL
Structure for UniProt ID HHH-rd1-0142 not found. Status code: 404
[Errno 2] No such file or directory: '/home/sareeves/PSLMs/data/domainome1/alphafold_structures/HHH-rd1-0142.pdb'
No file for /home/sareeves/PSLMs/data/domainome1/alphafold_structures/HHH-rd1-0142.pdb
O00308_PF00397_440
MIQEPALPPGWEMKYTSEGVRYFVDHNTRTTTFKDPRPGFESGTKQGSPGCYDR
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O00308_440-493.pdb
O00330_PF02817_181
RFRLSPAARNILEKHSLDCSQGTATGPRGIFTKEDALKLVQLKQTGK
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O00330_181-227.pdb
O14529_PF02376_1036
GIQEIVCMSPELDTYSITKRVKEVLTDNNLGQRLFGESILGLTQGSVSDLLSRPKPWHKLSLKGREPFVRMQLWLNDPHNVEKLRDMKK
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O14529_1036-1124.pdb
O14529_PF02376_895
EVDTLELTRQVKEKLCKNGICQRIFGEKVLGLSQGSVSDMLSRPKPWSKLTQKGREPFIRMQLWLSDQL
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O14529_895-963.pdb
O14640_PF00595_246
SLNIVTVTLNMERHHFLGISIVGQSNDRGDGGIYIGSIMKGGCVAADGRIEPGDMLLQVNDVNFENMSNDDAVRVLREIVSQTGPISLTVAKC
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O14640_246-338.pdb
O14640_PF00778_4
TKIIYHMDEEETPYLVKLPVCPERVTLADFKNVLSNRPVHAYKFFFKSMDQDFGVVKEEIFDDNAKLPCFNGRVVSWL
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O14640_4-81.pdb
O14776_PF01846_645
EAEIKAARERCIVPLEARMKQFKDMLLERGVSAFSTWEKELHKIVFDPRYLLLNPKERKQVFDQYVKTR
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O14776_645-713.pdb
O14776_PF01846_727
QAKEDFKKMMEECKFNPRATFSEFAAKHAKDSRFKAIEKMKDREALFNEF
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O14776_727-776.pdb
O14776_PF01846_793
EKIKSDFFELLSNHHLDSQSRWSKVKDKVESDPRYKCVDSSSMREDLFKQYIEKIAKNLDSE
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O14776_793-854.pdb
O14776_PF01846_897
EECIQNFKALLSDMVRSSDVSWSDTRRTLRKDHRWESGSLLEREEKEKLFNEHIEALTK
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O14776_897-955.pdb
O14776_PF01846_955
KKKREHFRQLLDETSCITLTSTWKEVKKIIKEDPRCIKFSSSDRKKQREFEEYIRD
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O14776_955-1010.pdb
O14813_PF00046_92
RIRTTFTSAQLKELERVFCETHYPDIYTREELALKIDLTEARVQVWFQNRRAKFRK
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O14813_92-147.pdb
O14901_PF00096_395
VCSFPGCRKTYFKSSHLKCHLRTH
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O14901_395-418.pdb
O14936_PF00595_488
VRLVQFQKNTDEPMGITLKMNELNHCIVCRIMHGGMIHRQGTLHVGDEIREINGISVANQTVEQLQKMLREMRGSITFKIVP
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O14936_488-569.pdb
O15151_PF00641_299
TSEDEWQCTECKKFNSPSKRYCFRCWCLRKD
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O15151_299-329.pdb
O15259_PF00018_152
STGEEYIAVGDFTCQQVGDLTFKKGEILLVIEKKPDGWWIAKDAKGNEGLVPRTYLEPYS
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O15259_152-211.pdb
O15265_PF08313_334
KRLSEREFDPDIHCGVIDLDTKKPCTRSLTCKTHSLTQRRCVQGRRKRFDVLLAEHKNKTR
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O15265_334-394.pdb
O15266_PF00046_119
RSRTNFTLEQLNELERLFDETHYPDCFMREELSQRLGLSEARVQVWFQNRRAKCRK
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O15266_119-174.pdb
O15344_PF00643_172
GLMCLEHEDEKVNMYCVTDDQLICCLCKLVGRHRDHQVAALSE
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O15344_172-214.pdb
O15350_PF07647_487
YHCDPSLVSFLTGLGCPNCIEYFTSQGLQSIYHLQNLTIEDLGALKIPEQYRMTIWRGLQDLK
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O15350_487-549.pdb
O15405_PF00505_256
QKPVSAYALFFRDTQCAIKGQNPNATFGEVSKIVASMWDSLGEEQKQVYKRKTEAAKKEYLKALAAYR
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O15405_256-323.pdb
O15541_PF00642_198
QPDICKDYKETGFAGFGDSCKFLHD
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O15541_198-222.pdb
O43167_PF00096_351
TCTVCSKCLTTKHSLLEHMSLH
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O43167_351-372.pdb
O43167_PF00096_435
TCEICGKSFTCKSSLQTHIRIH
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O43167_435-456.pdb
O43186_PF00046_41
RERTTFTRSQLEELECLFAKTQYPDVYAREEVALKINLPESRVQVWFKNRRAKCRQ
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O43186_41-96.pdb
O43295_PF00018_745
EQIEAIAKFDYMGRSPRELSFKKGCSLLLYHRASEDWWEGRHNGVDGLIPHQYIVVQD
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O43295_745-802.pdb
O43353_PF00619_438
QWIQSKREDIVNQMTECCLNQSLDALLSRDLIMKEDYELVSTKPTRTSKVRQLLDTTDIQGEEFAKVIVQKLKDNKQMGLQ
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O43353_438-518.pdb
O43374_PF00779_682
YHPGVFRGDKWSACHQKEKTGQGCDKTR
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O43374_682-709.pdb
O43395_PF01480_10
ELKPWIEKTVKRVLGFSEPTVVTCALNCVGKGMDKKKAADHLKPFLDDSTLRFVDKLFEAVEEGRSSR
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O43395_10-77.pdb
O43586_PF00018_361
AQEYRALYDYTCQNPDELDLSAGDILEVILEGEDGWWTVERNGQRGFVPGSYLEKL
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O43586_361-416.pdb
O60281_PF00096_808
TAKFTGCGKVYRSQGELEKHLDDH
Structure for UniProt ID O60281 not found. Status code: 404
[Errno 2] No such file or directory: '/home/sareeves/PSLMs/data/domainome1/alphafold_structures/O60281.pdb'
No file for /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O60281.pdb
O60293_PF10650_1186
CRFDLTGTCNDDDAQWQHI
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O60293_1186-1204.pdb
O60341_PF04433_186
DRMTSQEAACFPDIISGPQQTQKVFLFIRNRTLQLWLDNPKIQLTFECTLQQLEAPYNSDTVLVHRVHSYLERHGLINF
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O60341_186-264.pdb
O60481_PF00096_389
IAKVCDKSYTHPSSLRKHMKVH
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O60481_389-410.pdb
O60885_PF17035_607
AKPMSYEEKRQLSLDINKLPGEKLGRVVHIIQSREPSLKNSNPDEIEIDFETLKPSTLRELERYVTS
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O60885_607-673.pdb
O75112_PF00595_1
MSYSVTLTGPGPWGFRLQGGKDFNMPLTISRITPGSKCAQSQLSQGDLVVAIDGVNTDTMTHLEAQNKIKSASYNLSLTLQKS
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O75112_1-83.pdb
O75360_PF00046_71
RHRTTFSPVQLEQLESCFGRNQYPDIWARESLARDTGLSEARIQVWFQNRRAKQRK
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O75360_71-126.pdb
O75366_PF02209_785
LSEQDFVSVFGITRGQFCALPGWKQLQMKKEKGLF
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O75366_785-819.pdb
O75369_PF00630_1423
KVKIAGPGLGSGVRCRVLQSFTVDSSKAGLAPLEVRVLGPRGLVEPVNVVDNGDGTHTVTYTPSQEGPYMVSVKYADEEIPRSPFKVKVL
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O75369_1423-1512.pdb
O75369_PF00630_2109
CTVGSICDLNLKIPEINSSDMSAHVTSPSGRVTEAEIVPMGKNSHCVRFVPQEMGVHTVSVKYRGQHVTGSPFQFTVG
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O75369_2109-2186.pdb
O75369_PF00630_2289
RLTVMSLQESGLKVNQPCSFAIRLNGAKGKIDAKVHSPSGAVEECHVSELEPDKYAVRFIPHENGVHTIDVKFNGSHVVGSPFKVRVGEP
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O75369_2289-2378.pdb
O75382_PF00643_111
RPLSCPNHEGKTMEFYCECCETAMCGECRAGEHREHGTVLLRDV
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O75382_111-154.pdb
O75400_PF00397_176
TPAEQLLSKCPWKEYKSDSGKPYYYNSQTKESRWCKPKELEDLEGYQNTIV
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O75400_176-226.pdb
O75400_PF01846_395
EAKQAFKELLKEKRVPSNCSWEQAMKMIINDPRYSALAKLSEKKQAFNAY
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O75400_395-444.pdb
O75400_PF01846_459
KYKEAKESFQRFLENHEKMTSTTRYKKCEQMFGEMEVWNAISERDRLEIYEDVL
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O75400_459-512.pdb
O75400_PF01846_670
CRYHDEKKIIKDILKDKGFVVEVNTTFEDFVAIISSTKRSTTLDAGNIKLAFNSL
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O75400_670-724.pdb
O75400_PF01846_745
RKESAFKSMLKQCAPPIELDAVWEDIRERFVKEPAFEDITLESERKRIFKDFMHVLEHEC
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O75400_745-804.pdb
O75478_PF04433_375
KLNEKEKELCQMVRLVPGCYLEYKSALLNECNKQGGLRLAQARALIKIDVNKTRKIYDFLIREGYI
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O75478_375-440.pdb
O75534_PF00313_184
ARCQGVVCAMKECFGFIERGDVVKEIFFHYSEFKGDLETLQPGDDVEFTIKDRNGKEVATDVRLLPQGTVI
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O75534_184-254.pdb
O75534_PF00313_23
CLRETGVIEKLLTSYGFIQCSERQARLFFHCSQYNGNLQDLKVGDDVEFEVSSDRRTGKPIAVKLVKIK
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O75534_23-91.pdb
O75534_PF00313_347
CREMGVIAAMRDGFGFIKCVDRDVRMFFHFSEILDGNQLHIADEVEFTVVPDMLSAQRNHAIRIKKLPKGTV
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O75534_347-418.pdb
O75554_PF06220_8
QPKKFCDYCKCWICDNRPSVEFHERGKNHKENVAKR
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O75554_8-43.pdb
O75808_PF00641_4
VGEWSCVRCTFLNPCGQRQCSICEAPR
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O75808_4-30.pdb
O75953_PF00226_4
DYYKILGIPSGCNEDEIKKAYRKMALKYHPDKNKEPNAEEKFKEIAEAYDVLSDPKKRGLYD
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O75953_4-65.pdb
O75970_PF00595_1003
ESFERTINICKGNSSLGMTVSANKDGLGMIVRSIIHGGAISRDGRIAIGDCILSINEESTISVTNAQARAMLRRHSLIGPDIKITYVP
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O75970_1003-1090.pdb
O75970_PF00595_1860
LRTVEMKKGPTDSLGISICGGVGSPLGDVPIFIAMMHPTGVAAQTQKLRVGDRIVTICGTSTEGMTHTQAVNLLKNASGSIEMQV
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O75970_1860-1944.pdb
O75970_PF00595_372
ESETFDVELTKNVQGLGITICGYIGDKKLEPSGIFVKSITKSSAVEHDGRIQIGDQIIAVDGTNLQGFTNQQAVEVLRHTGQTVLLTLMRRG
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O75970_372-463.pdb
O75970_PF00595_693
MWEAGIQHIELEKGSKGLGFSILDYQDPIDPCSTVIIIRSLVPGGIAEKDGRLLPGDRLMFVNDVNLENSSLEEAVEALKGAPSGTVRIGVAKPLP
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O75970_693-788.pdb
O94830_PF00536_389
TLEEDLKKLQLSEFFDIFEKEKVDKECLALCTDRDLQEIGIPLGPRKKILNYFSTRKNS
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O94830_389-447.pdb
O94885_PF00536_630
GRPPQPKSVEDLLDRINLKEHMPTFLFNGYEDLDTFKLLEEEDLDELNIRDPEHRCVLLTAVELLQEYDSN
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O94885_630-700.pdb
O94929_PF00412_149
SHCAGCKEEIKHGQSLLCLDKQWHVSCFKCQTCSVILTGEYISKDGVPYCESDYHAQF
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O94929_149-206.pdb
O94929_PF00412_210
CETCDRYISGRVLECGGKHYHPTCARCVRCHQMFTEGEEMYLTGSEVWHPICKQAAR
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O94929_210-266.pdb
O94993_PF00505_338
KRPMNAFMVWCRIHRPALAKANPAANNAEISVQLGLEWNKLSEEQKKPYYDEAQKIKEKHREEFPGW
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O94993_338-404.pdb
O95076_PF00046_155
RNRTTFSTFQLEELEKVFQKTHYPDVYCREQLALRTDLTEARVQVWFQNRRAKWRK
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O95076_155-210.pdb
O95155_PF04564_1229
PDEFRDPLMDTLMTDPVRLPSGTIMDRSIILRHLLNSPTDPFNRQTLTESMLEPVPELKEQIQCWMREKQN
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O95155_1229-1299.pdb
O95218_PF00641_11
GDWICPDKKCGNVNFCRRTSCNRCG
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O95218_11-35.pdb
O95218_PF00641_9
SDGDWICPDKKCGNVNFCRRTSCNRCG
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O95218_9-35.pdb
O95267_PF00130_539
GFPHNFQETTYLKPTFCDNCCGFLWGVIKQGYRCKDCGMNCHKQCKDLVVFECKK
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O95267_539-593.pdb
O95343_PF00046_212
CFKERTRSLLREWYLQDPYPNPSKKRELCQATGLTPTQVGNWFKNRRQRDR
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O95343_212-262.pdb
O95409_PF18366_250
QCIKQELICKWIDPEQLSNPKKSANKTFSTMHELVTHVSVEHVGGP
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O95409_250-295.pdb
O95475_PF00046_134
CFKERTRHLLREWYLQDPYPNPSKKRELCQATGLTPTQVGNWFKNRRQRDR
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O95475_134-184.pdb
O95714_PF11515_2555
ADFLSNDDYCVYVRENIQVGMMVRCCRAYEEVCEGDVGKVIKLDRDGLHDLNVQCDWQQKGGTYWVRYIHVELIGY
Structure for UniProt ID O95714 not found. Status code: 404
[Errno 2] No such file or directory: '/home/sareeves/PSLMs/data/domainome1/alphafold_structures/O95714.pdb'
No file for /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O95714.pdb
O95718_PF00105_100
KRLCLVCGDICSGYHYGVASCEACKAFFKRTIQGNIEYSCPATNECEITKRRRKSCQACRFMKCLKVGMLKEGVRLD
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O95718_100-176.pdb
O95789_PF06467_427
KLKCQHCNHLFCTKPELLFYKGKMFLFCGKNCSDEYKKKN
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O95789_427-466.pdb
O95789_PF06467_469
VCMCDYCKLQKIIKETVRFSGVDKPFCSEVCKFLSA
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O95789_469-504.pdb
O95793_PF00035_183
KSEISQVFEICLKRNLPVNFEVARESGPPHMKNFVTKVSVGEFVGEGEGKSKKISKKNAAIAVLEEL
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O95793_183-249.pdb
O95817_PF00397_11
QVCSGNGDRDPLPPGWEIKIDPQTGWPFFVDHNSRTTTWNDPRVPSEGP
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O95817_11-59.pdb
O95835_PF00627_98
TSEVNPQMLQDLQCAGFDEDMVIQALQKTNNRSIEAAIEFISKM
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/O95835_98-141.pdb
P00519_PF00018_64
NLFVALYDFVCSGDNTLSITKGEKLRVLGYNHNGEWCEAQTKNGQGWVPSNYITPVN
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/P00519_64-120.pdb
P01053_PF00280_22
KTEWPELVGKSVEECKKVILQDKPEAQIIVLPVGTIVTMEYRIDRVRLFVDKLDNIAQVPRVG
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/P01053_22-84.pdb
P02417_PF01281_1
MKVIFLKDVKGKGKKGEIKNVCDGYANNFLFKQGLAIEATPANLKAL
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/P02417_1-47.pdb
P02549_PF00018_979
EQRVMALYDFQCRSPREVTMKKGDVLTLLSSINKDWWKVEAADHQGIVPAVYVRRLAH
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/P02549_979-1036.pdb
P02585_PF13499_1
MTDQQAEARSYLSEEMICEFKAAFDMFDADGGGDISVKELGTVMRMLGQTPTKEELDAIIEEVDEDGSGTIDFEEFLVMMVRQ
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/P02585_1-83.pdb
P02633_PF01023_1
MSAKKSPEELKGIFEKYCAKEGDPNQLSKEELKLLLQTEFPSLLKGPSTLDELFEELDKNGDGEVSFEEFQVLVKKISQ
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/P02633_1-79.pdb
P02640_PF02209_762
KLETFPLDVLVNTCAEDLPRGVDPSRKENHLSDEDFKAVFGMTRSAFANLPLWKQQNLKKEKGLF
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/P02640_762-826.pdb
P02640_PF02209_792
LSDEDFKAVFGMTRSCFANLPLWKQQNLKKEKGLF
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/P02640_792-826.pdb
P03034_PF01381_4
KKKPLTQEQLEDCRRLKAIYEKKKNELGLSQESVADKMGMGQSGVGALFNGINALNAYNAALLAKILKVSVEEFSP
Structure for UniProt ID P03034 not found. Status code: 404
[Errno 2] No such file or directory: '/home/sareeves/PSLMs/data/domainome1/alphafold_structures/P03034.pdb'
No file for /home/sareeves/PSLMs/data/domainome1/alphafold_structures/P03034.pdb
P04049_PF02196_58
IRVFLPNKQRTVVNVRNGMSLHDCLMKCLKVRGLQPECCAVFRLLHEHKGKKARLDWNTDAASLIGEELQV
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/P04049_58-128.pdb
P04150_PF00105_419
KLCLVCSDECSGCHYGVLTCGSCKVFFKRAVEGQHNYLCAGRNDCIIDKIRRKNCPACRYRKCLQAGMNLEARKTK
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/P04150_419-494.pdb
P05813_PF00030_31
WKITIYDQENFQGKRMEFTSSCPNVSERSFDNVRSLKVESGCWIGYEHTSFCGQQFILERGEYPRWDAWSGSNAYHIERLMSFRPICSA
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/P05813_31-119.pdb
P06239_PF00018_63
DNLVIALHSYEPSHDGDLGFEKGEQLRILEQSGEWWKCQSLTTGQEGFIPFNFVAKAN
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/P06239_63-120.pdb
P06241_PF00018_83
GVTLFVALYDYECRTEDDLSFHKGEKFQILNSSEGDWWEARSLTTGETGYIPSNYVAPVDS
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/P06241_83-143.pdb
P07315_PF00030_4
ITFYEDRCFQGRSYETTTDCPNLQPYFSRCNSIRVESGCWMLYERPNYQGQQYLLRRGEYPDYQQWMGLSDSIRSC
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/P07315_4-79.pdb
P07315_PF00030_91
RLYEREDHKGLMMELSEDCPSIQDRFHLSEIRSLHVLEGCWVLYELPNYRGRQYLLRPQEYRRCQDWGCMDAKAGSLRRV
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/P07315_91-170.pdb
P07316_PF00030_1
MGKITFYEDRCFQGRSYECTTDCPNLQPYFSRCNSIRVESGCWMIYERPNYQGHQYFLRRGEYPDYQQWMGLSDSIRSCCLIPP
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/P07316_1-84.pdb
P07316_PF00030_87
GCYRMKIYDRDELRGQMSELTDDCISVQDRFHLTEIHSLNVLEGSWILYEMPNYRGRQYLLRPGEYRRFLDWGAPNAKVGSLRRVMD
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/P07316_87-173.pdb
P07320_PF00030_90
IRLYEREDYRGQMIEFTEDCSCLQDRFRFNEIHSLNVLEGSWVLYELSNYRGRQYLLMPGDYRRYQDWGCTNARVGSLRRV
Truncated PDB saved to /home/sareeves/PSLMs/data/domainome1/alphafold_structures/P07320_90-170.pdb
P07751_PF00018_968
GKELVLALYDYQEKSPREVTMKKGDILTLLNSTNKDWWKVEVNDRQGFVPCAYVKKLDP

In [5]:
failed_assertions

[('Q13472_PF06839_896', 'A', 25, 'C'),
 ('Q13472_PF06839_896', 'A', 25, 'D'),
 ('Q13472_PF06839_896', 'A', 25, 'E'),
 ('Q13472_PF06839_896', 'A', 25, 'F'),
 ('Q13472_PF06839_896', 'A', 25, 'G'),
 ('Q13472_PF06839_896', 'A', 25, 'H'),
 ('Q13472_PF06839_896', 'A', 25, 'I'),
 ('Q13472_PF06839_896', 'A', 25, 'K'),
 ('Q13472_PF06839_896', 'A', 25, 'L'),
 ('Q13472_PF06839_896', 'A', 25, 'M'),
 ('Q13472_PF06839_896', 'A', 25, 'N'),
 ('Q13472_PF06839_896', 'A', 25, 'P'),
 ('Q13472_PF06839_896', 'A', 25, 'Q'),
 ('Q13472_PF06839_896', 'A', 25, 'R'),
 ('Q13472_PF06839_896', 'A', 25, 'S'),
 ('Q13472_PF06839_896', 'A', 25, 'T'),
 ('Q13472_PF06839_896', 'A', 25, 'V'),
 ('Q13472_PF06839_896', 'A', 25, 'W'),
 ('Q13472_PF06839_896', 'A', 25, 'Y'),
 ('Q13472_PF06839_896', 'C', -1, 'A'),
 ('Q13472_PF06839_896', 'C', -1, 'D'),
 ('Q13472_PF06839_896', 'C', -1, 'E'),
 ('Q13472_PF06839_896', 'C', -1, 'F'),
 ('Q13472_PF06839_896', 'C', -1, 'G'),
 ('Q13472_PF06839_896', 'C', -1, 'H'),
 ('Q13472_PF06839_896', 'C', -1, 'I'),
 ('Q13472_PF06839_896', 'C', -1, 'K'),
 ('Q13472_PF06839_896', 'C', -1, 'L'),
 ('Q13472_PF06839_896', 'C', -1, 'M'),
 ('Q13472_PF06839_896', 'C', -1, 'N'),
 ('Q13472_PF06839_896', 'C', -1, 'P'),
 ('Q13472_PF06839_896', 'C', -1, 'Q'),
 ('Q13472_PF06839_896', 'C', -1, 'R'),
 ('Q13472_PF06839_896', 'C', -1, 'S'),
 ('Q13472_PF06839_896', 'C', -1, 'T'),
 ('Q13472_PF06839_896', 'C', -1, 'V'),
 ('Q13472_PF06839_896', 'C', -1, 'W'),
 ('Q13472_PF06839_896', 'C', -1, 'Y'),
 ('Q13472_PF06839_896', 'C', 24, 'A'),
 ('Q13472_PF06839_896', 'C', 24, 'D'),
 ('Q13472_PF06839_896', 'C', 24, 'E'),
 ('Q13472_PF06839_896', 'C', 24, 'F'),
 ('Q13472_PF06839_896', 'C', 24, 'G'),
 ('Q13472_PF06839_896', 'C', 24, 'H'),
 ('Q13472_PF06839_896', 'C', 24, 'I'),
 ('Q13472_PF06839_896', 'C', 24, 'K'),
 ('Q13472_PF06839_896', 'C', 24, 'L'),
 ('Q13472_PF06839_896', 'C', 24, 'M'),
 ('Q13472_PF06839_896', 'C', 24, 'N'),
 ('Q13472_PF06839_896', 'C', 24, 'P'),
 ('Q13472_PF06839_896', 'C', 24, 'Q'),
 ('Q13472_PF06839_896', 'C', 24, 'R'),
 ('Q13472_PF06839_896', 'C', 24, 'S'),
 ('Q13472_PF06839_896', 'C', 24, 'T'),
 ('Q13472_PF06839_896', 'C', 24, 'V'),
 ('Q13472_PF06839_896', 'C', 24, 'W'),
 ('Q13472_PF06839_896', 'C', 24, 'Y'),
 ('Q13472_PF06839_896', 'C', 32, 'A'),
 ('Q13472_PF06839_896', 'C', 32, 'D'),
 ('Q13472_PF06839_896', 'C', 32, 'E'),
 ('Q13472_PF06839_896', 'C', 32, 'F'),
 ('Q13472_PF06839_896', 'C', 32, 'G'),
 ('Q13472_PF06839_896', 'C', 32, 'H'),
 ('Q13472_PF06839_896', 'C', 32, 'I'),
 ('Q13472_PF06839_896', 'C', 32, 'K'),
 ('Q13472_PF06839_896', 'C', 32, 'L'),
 ('Q13472_PF06839_896', 'C', 32, 'M'),
 ('Q13472_PF06839_896', 'C', 32, 'N'),
 ('Q13472_PF06839_896', 'C', 32, 'P'),
 ('Q13472_PF06839_896', 'C', 32, 'Q'),
 ('Q13472_PF06839_896', 'C', 32, 'R'),
 ('Q13472_PF06839_896', 'C', 32, 'S'),
 ('Q13472_PF06839_896', 'C', 32, 'T'),
 ('Q13472_PF06839_896', 'C', 32, 'V'),
 ('Q13472_PF06839_896', 'C', 32, 'W'),
 ('Q13472_PF06839_896', 'C', 32, 'Y'),
 ('Q13472_PF06839_896', 'C', 1, 'A'),
 ('Q13472_PF06839_896', 'C', 1, 'D'),
 ('Q13472_PF06839_896', 'C', 1, 'E'),
 ('Q13472_PF06839_896', 'C', 1, 'F'),
 ('Q13472_PF06839_896', 'C', 1, 'G'),
 ('Q13472_PF06839_896', 'C', 1, 'H'),
 ('Q13472_PF06839_896', 'C', 1, 'I'),
 ('Q13472_PF06839_896', 'C', 1, 'K'),
 ('Q13472_PF06839_896', 'C', 1, 'L'),
 ('Q13472_PF06839_896', 'C', 1, 'M'),
 ('Q13472_PF06839_896', 'C', 1, 'N'),
 ('Q13472_PF06839_896', 'C', 1, 'P'),
 ('Q13472_PF06839_896', 'C', 1, 'Q'),
 ('Q13472_PF06839_896', 'C', 1, 'R'),
 ('Q13472_PF06839_896', 'C', 1, 'S'),
 ('Q13472_PF06839_896', 'C', 1, 'T'),
 ('Q13472_PF06839_896', 'C', 1, 'V'),
 ('Q13472_PF06839_896', 'C', 1, 'W'),
 ('Q13472_PF06839_896', 'C', 1, 'Y'),
 ('Q13472_PF06839_896', 'D', 13, 'A'),
 ('Q13472_PF06839_896', 'D', 13, 'C'),
 ('Q13472_PF06839_896', 'D', 13, 'E'),
 ('Q13472_PF06839_896', 'D', 13, 'F'),
 ('Q13472_PF06839_896', 'D', 13, 'G'),
 ('Q13472_PF06839_896', 'D', 13, 'H'),
 ('Q13472_PF06839_896', 'D', 13, 'I'),
 ('Q13472_PF06839_896', 'D', 13, 'K'),
 ('Q13472_PF06839_896', 'D', 13, 'L'),
 ('Q13472_PF06839_896', 'D', 13, 'M'),
 ('Q13472_PF06839_896', 'D', 13, 'N'),
 ('Q13472_PF06839_896', 'D', 13, 'P'),
 ('Q13472_PF06839_896', 'D', 13, 'Q'),
 ('Q13472_PF06839_896', 'D', 13, 'R'),
 ('Q13472_PF06839_896', 'D', 13, 'S'),
 ('Q13472_PF06839_896', 'D', 13, 'T'),
 ('Q13472_PF06839_896', 'D', 13, 'V'),
 ('Q13472_PF06839_896', 'D', 13, 'W'),
 ('Q13472_PF06839_896', 'D', 13, 'Y'),
 ('Q13472_PF06839_896', 'D', 39, 'A'),
 ('Q13472_PF06839_896', 'D', 39, 'C'),
 ('Q13472_PF06839_896', 'D', 39, 'E'),
 ('Q13472_PF06839_896', 'D', 39, 'F'),
 ('Q13472_PF06839_896', 'D', 39, 'G'),
 ('Q13472_PF06839_896', 'D', 39, 'H'),
 ('Q13472_PF06839_896', 'D', 39, 'I'),
 ('Q13472_PF06839_896', 'D', 39, 'K'),
 ('Q13472_PF06839_896', 'D', 39, 'L'),
 ('Q13472_PF06839_896', 'D', 39, 'M'),
 ('Q13472_PF06839_896', 'D', 39, 'N'),
 ('Q13472_PF06839_896', 'D', 39, 'P'),
 ('Q13472_PF06839_896', 'D', 39, 'Q'),
 ('Q13472_PF06839_896', 'D', 39, 'R'),
 ('Q13472_PF06839_896', 'D', 39, 'S'),
 ('Q13472_PF06839_896', 'D', 39, 'T'),
 ('Q13472_PF06839_896', 'D', 39, 'V'),
 ('Q13472_PF06839_896', 'D', 39, 'W'),
 ('Q13472_PF06839_896', 'D', 39, 'Y'),
 ('Q13472_PF06839_896', 'E', 29, 'A'),
 ('Q13472_PF06839_896', 'E', 29, 'C'),
 ('Q13472_PF06839_896', 'E', 29, 'D'),
 ('Q13472_PF06839_896', 'E', 29, 'F'),
 ('Q13472_PF06839_896', 'E', 29, 'G'),
 ('Q13472_PF06839_896', 'E', 29, 'H'),
 ('Q13472_PF06839_896', 'E', 29, 'I'),
 ('Q13472_PF06839_896', 'E', 29, 'K'),
 ('Q13472_PF06839_896', 'E', 29, 'L'),
 ('Q13472_PF06839_896', 'E', 29, 'M'),
 ('Q13472_PF06839_896', 'E', 29, 'N'),
 ('Q13472_PF06839_896', 'E', 29, 'P'),
 ('Q13472_PF06839_896', 'E', 29, 'Q'),
 ('Q13472_PF06839_896', 'E', 29, 'R'),
 ('Q13472_PF06839_896', 'E', 29, 'S'),
 ('Q13472_PF06839_896', 'E', 29, 'T'),
 ('Q13472_PF06839_896', 'E', 29, 'V'),
 ('Q13472_PF06839_896', 'E', 29, 'W'),
 ('Q13472_PF06839_896', 'E', 29, 'Y'),
 ('Q13472_PF06839_896', 'E', 40, 'A'),
 ('Q13472_PF06839_896', 'E', 40, 'C'),
 ('Q13472_PF06839_896', 'E', 40, 'D'),
 ('Q13472_PF06839_896', 'E', 40, 'F'),
 ('Q13472_PF06839_896', 'E', 40, 'G'),
 ('Q13472_PF06839_896', 'E', 40, 'H'),
 ('Q13472_PF06839_896', 'E', 40, 'I'),
 ('Q13472_PF06839_896', 'E', 40, 'K'),
 ('Q13472_PF06839_896', 'E', 40, 'L'),
 ('Q13472_PF06839_896', 'E', 40, 'M'),
 ('Q13472_PF06839_896', 'E', 40, 'N'),
 ('Q13472_PF06839_896', 'E', 40, 'P'),
 ('Q13472_PF06839_896', 'E', 40, 'Q'),
 ('Q13472_PF06839_896', 'E', 40, 'R'),
 ('Q13472_PF06839_896', 'E', 40, 'S'),
 ('Q13472_PF06839_896', 'E', 40, 'T'),
 ('Q13472_PF06839_896', 'E', 40, 'V'),
 ('Q13472_PF06839_896', 'E', 40, 'W'),
 ('Q13472_PF06839_896', 'E', 40, 'Y'),
 ('Q13472_PF06839_896', 'F', 21, 'A'),
 ('Q13472_PF06839_896', 'F', 21, 'C'),
 ('Q13472_PF06839_896', 'F', 21, 'D'),
 ('Q13472_PF06839_896', 'F', 21, 'E'),
 ('Q13472_PF06839_896', 'F', 21, 'G'),
 ('Q13472_PF06839_896', 'F', 21, 'H'),
 ('Q13472_PF06839_896', 'F', 21, 'I'),
 ('Q13472_PF06839_896', 'F', 21, 'K'),
 ('Q13472_PF06839_896', 'F', 21, 'L'),
 ('Q13472_PF06839_896', 'F', 21, 'M'),
 ('Q13472_PF06839_896', 'F', 21, 'N'),
 ('Q13472_PF06839_896', 'F', 21, 'P'),
 ('Q13472_PF06839_896', 'F', 21, 'Q'),
 ('Q13472_PF06839_896', 'F', 21, 'R'),
 ('Q13472_PF06839_896', 'F', 21, 'S'),
 ('Q13472_PF06839_896', 'F', 21, 'T'),
 ('Q13472_PF06839_896', 'F', 21, 'V'),
 ('Q13472_PF06839_896', 'F', 21, 'W'),
 ('Q13472_PF06839_896', 'F', 21, 'Y'),
 ('Q13472_PF06839_896', 'F', 34, 'A'),
 ('Q13472_PF06839_896', 'F', 34, 'C'),
 ('Q13472_PF06839_896', 'F', 34, 'D'),
 ('Q13472_PF06839_896', 'F', 34, 'E'),
 ('Q13472_PF06839_896', 'F', 34, 'G'),
 ('Q13472_PF06839_896', 'F', 34, 'H'),
 ('Q13472_PF06839_896', 'F', 34, 'I'),
 ('Q13472_PF06839_896', 'F', 34, 'K'),
 ('Q13472_PF06839_896', 'F', 34, 'L'),
 ('Q13472_PF06839_896', 'F', 34, 'M'),
 ('Q13472_PF06839_896', 'F', 34, 'N'),
 ('Q13472_PF06839_896', 'F', 34, 'P'),
 ('Q13472_PF06839_896', 'F', 34, 'Q'),
 ('Q13472_PF06839_896', 'F', 34, 'R'),
 ('Q13472_PF06839_896', 'F', 34, 'S'),
 ('Q13472_PF06839_896', 'F', 34, 'T'),
 ('Q13472_PF06839_896', 'F', 34, 'V'),
 ('Q13472_PF06839_896', 'F', 34, 'W'),
 ('Q13472_PF06839_896', 'F', 34, 'Y'),
 ('Q13472_PF06839_896', 'F', 35, 'A'),
 ('Q13472_PF06839_896', 'F', 35, 'C'),
 ('Q13472_PF06839_896', 'F', 35, 'D'),
 ('Q13472_PF06839_896', 'F', 35, 'E'),
 ('Q13472_PF06839_896', 'F', 35, 'G'),
 ('Q13472_PF06839_896', 'F', 35, 'H'),
 ('Q13472_PF06839_896', 'F', 35, 'I'),
 ('Q13472_PF06839_896', 'F', 35, 'K'),
 ('Q13472_PF06839_896', 'F', 35, 'L'),
 ('Q13472_PF06839_896', 'F', 35, 'M'),
 ('Q13472_PF06839_896', 'F', 35, 'N'),
 ('Q13472_PF06839_896', 'F', 35, 'P'),
 ('Q13472_PF06839_896', 'F', 35, 'Q'),
 ('Q13472_PF06839_896', 'F', 35, 'R'),
 ('Q13472_PF06839_896', 'F', 35, 'S'),
 ('Q13472_PF06839_896', 'F', 35, 'T'),
 ('Q13472_PF06839_896', 'F', 35, 'V'),
 ('Q13472_PF06839_896', 'F', 35, 'W'),
 ('Q13472_PF06839_896', 'F', 35, 'Y'),
 ('Q13472_PF06839_896', 'G', 14, 'A'),
 ('Q13472_PF06839_896', 'G', 14, 'C'),
 ('Q13472_PF06839_896', 'G', 14, 'D'),
 ('Q13472_PF06839_896', 'G', 14, 'E'),
 ('Q13472_PF06839_896', 'G', 14, 'F'),
 ('Q13472_PF06839_896', 'G', 14, 'H'),
 ('Q13472_PF06839_896', 'G', 14, 'I'),
 ('Q13472_PF06839_896', 'G', 14, 'K'),
 ('Q13472_PF06839_896', 'G', 14, 'L'),
 ('Q13472_PF06839_896', 'G', 14, 'M'),
 ('Q13472_PF06839_896', 'G', 14, 'N'),
 ('Q13472_PF06839_896', 'G', 14, 'P'),
 ('Q13472_PF06839_896', 'G', 14, 'Q'),
 ('Q13472_PF06839_896', 'G', 14, 'R'),
 ('Q13472_PF06839_896', 'G', 14, 'S'),
 ('Q13472_PF06839_896', 'G', 14, 'T'),
 ('Q13472_PF06839_896', 'G', 14, 'V'),
 ('Q13472_PF06839_896', 'G', 14, 'W'),
 ('Q13472_PF06839_896', 'G', 14, 'Y'),
 ('Q13472_PF06839_896', 'G', 18, 'A'),
 ('Q13472_PF06839_896', 'G', 18, 'C'),
 ('Q13472_PF06839_896', 'G', 18, 'D'),
 ('Q13472_PF06839_896', 'G', 18, 'E'),
 ('Q13472_PF06839_896', 'G', 18, 'F'),
 ('Q13472_PF06839_896', 'G', 18, 'H'),
 ('Q13472_PF06839_896', 'G', 18, 'I'),
 ('Q13472_PF06839_896', 'G', 18, 'K'),
 ('Q13472_PF06839_896', 'G', 18, 'L'),
 ('Q13472_PF06839_896', 'G', 18, 'M'),
 ('Q13472_PF06839_896', 'G', 18, 'N'),
 ('Q13472_PF06839_896', 'G', 18, 'P'),
 ('Q13472_PF06839_896', 'G', 18, 'Q'),
 ('Q13472_PF06839_896', 'G', 18, 'R'),
 ('Q13472_PF06839_896', 'G', 18, 'S'),
 ('Q13472_PF06839_896', 'G', 18, 'T'),
 ('Q13472_PF06839_896', 'G', 18, 'V'),
 ('Q13472_PF06839_896', 'G', 18, 'W'),
 ('Q13472_PF06839_896', 'G', 18, 'Y'),
 ('Q13472_PF06839_896', 'G', 33, 'A'),
 ('Q13472_PF06839_896', 'G', 33, 'C'),
 ('Q13472_PF06839_896', 'G', 33, 'D'),
 ('Q13472_PF06839_896', 'G', 33, 'E'),
 ('Q13472_PF06839_896', 'G', 33, 'F'),
 ('Q13472_PF06839_896', 'G', 33, 'H'),
 ('Q13472_PF06839_896', 'G', 33, 'I'),
 ('Q13472_PF06839_896', 'G', 33, 'K'),
 ('Q13472_PF06839_896', 'G', 33, 'L'),
 ('Q13472_PF06839_896', 'G', 33, 'M'),
 ('Q13472_PF06839_896', 'G', 33, 'N'),
 ('Q13472_PF06839_896', 'G', 33, 'P'),
 ('Q13472_PF06839_896', 'G', 33, 'Q'),
 ('Q13472_PF06839_896', 'G', 33, 'R'),
 ('Q13472_PF06839_896', 'G', 33, 'S'),
 ('Q13472_PF06839_896', 'G', 33, 'T'),
 ('Q13472_PF06839_896', 'G', 33, 'V'),
 ('Q13472_PF06839_896', 'G', 33, 'W'),
 ('Q13472_PF06839_896', 'G', 33, 'Y'),
 ('Q13472_PF06839_896', 'H', 22, 'A'),
 ('Q13472_PF06839_896', 'H', 22, 'C'),
 ('Q13472_PF06839_896', 'H', 22, 'D'),
 ('Q13472_PF06839_896', 'H', 22, 'E'),
 ('Q13472_PF06839_896', 'H', 22, 'F'),
 ('Q13472_PF06839_896', 'H', 22, 'G'),
 ('Q13472_PF06839_896', 'H', 22, 'I'),
 ('Q13472_PF06839_896', 'H', 22, 'K'),
 ('Q13472_PF06839_896', 'H', 22, 'L'),
 ('Q13472_PF06839_896', 'H', 22, 'M'),
 ('Q13472_PF06839_896', 'H', 22, 'N'),
 ('Q13472_PF06839_896', 'H', 22, 'P'),
 ('Q13472_PF06839_896', 'H', 22, 'Q'),
 ('Q13472_PF06839_896', 'H', 22, 'R'),
 ('Q13472_PF06839_896', 'H', 22, 'S'),
 ('Q13472_PF06839_896', 'H', 22, 'T'),
 ('Q13472_PF06839_896', 'H', 22, 'V'),
 ('Q13472_PF06839_896', 'H', 22, 'W'),
 ('Q13472_PF06839_896', 'H', 22, 'Y'),
 ('Q13472_PF06839_896', 'K', 12, 'A'),
 ('Q13472_PF06839_896', 'K', 12, 'C'),
 ('Q13472_PF06839_896', 'K', 12, 'D'),
 ('Q13472_PF06839_896', 'K', 12, 'E'),
 ('Q13472_PF06839_896', 'K', 12, 'F'),
 ('Q13472_PF06839_896', 'K', 12, 'G'),
 ('Q13472_PF06839_896', 'K', 12, 'H'),
 ('Q13472_PF06839_896', 'K', 12, 'I'),
 ('Q13472_PF06839_896', 'K', 12, 'L'),
 ('Q13472_PF06839_896', 'K', 12, 'M'),
 ('Q13472_PF06839_896', 'K', 12, 'N'),
 ('Q13472_PF06839_896', 'K', 12, 'P'),
 ('Q13472_PF06839_896', 'K', 12, 'Q'),
 ('Q13472_PF06839_896', 'K', 12, 'R'),
 ('Q13472_PF06839_896', 'K', 12, 'S'),
 ('Q13472_PF06839_896', 'K', 12, 'T'),
 ('Q13472_PF06839_896', 'K', 12, 'V'),
 ('Q13472_PF06839_896', 'K', 12, 'W'),
 ('Q13472_PF06839_896', 'K', 12, 'Y'),
 ('Q13472_PF06839_896', 'K', 17, 'A'),
 ('Q13472_PF06839_896', 'K', 17, 'C'),
 ('Q13472_PF06839_896', 'K', 17, 'D'),
 ('Q13472_PF06839_896', 'K', 17, 'E'),
 ('Q13472_PF06839_896', 'K', 17, 'F'),
 ('Q13472_PF06839_896', 'K', 17, 'G'),
 ('Q13472_PF06839_896', 'K', 17, 'H'),
 ('Q13472_PF06839_896', 'K', 17, 'I'),
 ('Q13472_PF06839_896', 'K', 17, 'L'),
 ('Q13472_PF06839_896', 'K', 17, 'M'),
 ('Q13472_PF06839_896', 'K', 17, 'N'),
 ('Q13472_PF06839_896', 'K', 17, 'P'),
 ('Q13472_PF06839_896', 'K', 17, 'Q'),
 ('Q13472_PF06839_896', 'K', 17, 'R'),
 ('Q13472_PF06839_896', 'K', 17, 'S'),
 ('Q13472_PF06839_896', 'K', 17, 'T'),
 ('Q13472_PF06839_896', 'K', 17, 'V'),
 ('Q13472_PF06839_896', 'K', 17, 'W'),
 ('Q13472_PF06839_896', 'K', 17, 'Y'),
 ('Q13472_PF06839_896', 'K', 26, 'A'),
 ('Q13472_PF06839_896', 'K', 26, 'C'),
 ('Q13472_PF06839_896', 'K', 26, 'D'),
 ('Q13472_PF06839_896', 'K', 26, 'E'),
 ('Q13472_PF06839_896', 'K', 26, 'F'),
 ('Q13472_PF06839_896', 'K', 26, 'G'),
 ('Q13472_PF06839_896', 'K', 26, 'H'),
 ('Q13472_PF06839_896', 'K', 26, 'I'),
 ('Q13472_PF06839_896', 'K', 26, 'L'),
 ('Q13472_PF06839_896', 'K', 26, 'M'),
 ('Q13472_PF06839_896', 'K', 26, 'N'),
 ('Q13472_PF06839_896', 'K', 26, 'P'),
 ('Q13472_PF06839_896', 'K', 26, 'Q'),
 ('Q13472_PF06839_896', 'K', 26, 'R'),
 ('Q13472_PF06839_896', 'K', 26, 'S'),
 ('Q13472_PF06839_896', 'K', 26, 'T'),
 ('Q13472_PF06839_896', 'K', 26, 'V'),
 ('Q13472_PF06839_896', 'K', 26, 'W'),
 ('Q13472_PF06839_896', 'K', 26, 'Y'),
 ('Q13472_PF06839_896', 'L', 0, 'A'),
 ('Q13472_PF06839_896', 'L', 0, 'C'),
 ('Q13472_PF06839_896', 'L', 0, 'D'),
 ('Q13472_PF06839_896', 'L', 0, 'E'),
 ('Q13472_PF06839_896', 'L', 0, 'F'),
 ('Q13472_PF06839_896', 'L', 0, 'G'),
 ('Q13472_PF06839_896', 'L', 0, 'H'),
 ('Q13472_PF06839_896', 'L', 0, 'I'),
 ('Q13472_PF06839_896', 'L', 0, 'K'),
 ('Q13472_PF06839_896', 'L', 0, 'M'),
 ('Q13472_PF06839_896', 'L', 0, 'N'),
 ('Q13472_PF06839_896', 'L', 0, 'P'),
 ('Q13472_PF06839_896', 'L', 0, 'Q'),
 ('Q13472_PF06839_896', 'L', 0, 'R'),
 ('Q13472_PF06839_896', 'L', 0, 'S'),
 ('Q13472_PF06839_896', 'L', 0, 'T'),
 ('Q13472_PF06839_896', 'L', 0, 'V'),
 ('Q13472_PF06839_896', 'L', 0, 'W'),
 ('Q13472_PF06839_896', 'L', 0, 'Y'),
 ('Q13472_PF06839_896', 'N', 16, 'A'),
 ('Q13472_PF06839_896', 'N', 16, 'C'),
 ('Q13472_PF06839_896', 'N', 16, 'D'),
 ('Q13472_PF06839_896', 'N', 16, 'E'),
 ('Q13472_PF06839_896', 'N', 16, 'F'),
 ('Q13472_PF06839_896', 'N', 16, 'G'),
 ('Q13472_PF06839_896', 'N', 16, 'H'),
 ('Q13472_PF06839_896', 'N', 16, 'I'),
 ('Q13472_PF06839_896', 'N', 16, 'K'),
 ('Q13472_PF06839_896', 'N', 16, 'L'),
 ('Q13472_PF06839_896', 'N', 16, 'M'),
 ('Q13472_PF06839_896', 'N', 16, 'P'),
 ('Q13472_PF06839_896', 'N', 16, 'Q'),
 ('Q13472_PF06839_896', 'N', 16, 'R'),
 ('Q13472_PF06839_896', 'N', 16, 'S'),
 ('Q13472_PF06839_896', 'N', 16, 'T'),
 ('Q13472_PF06839_896', 'N', 16, 'V'),
 ('Q13472_PF06839_896', 'N', 16, 'W'),
 ('Q13472_PF06839_896', 'N', 16, 'Y'),
 ('Q13472_PF06839_896', 'N', 41, 'A'),
 ('Q13472_PF06839_896', 'N', 41, 'C'),
 ('Q13472_PF06839_896', 'N', 41, 'D'),
 ('Q13472_PF06839_896', 'N', 41, 'E'),
 ('Q13472_PF06839_896', 'N', 41, 'F'),
 ('Q13472_PF06839_896', 'N', 41, 'G'),
 ('Q13472_PF06839_896', 'N', 41, 'H'),
 ('Q13472_PF06839_896', 'N', 41, 'I'),
 ('Q13472_PF06839_896', 'N', 41, 'K'),
 ('Q13472_PF06839_896', 'N', 41, 'L'),
 ('Q13472_PF06839_896', 'N', 41, 'M'),
 ('Q13472_PF06839_896', 'N', 41, 'P'),
 ('Q13472_PF06839_896', 'N', 41, 'Q'),
 ('Q13472_PF06839_896', 'N', 41, 'R'),
 ('Q13472_PF06839_896', 'N', 41, 'S'),
 ('Q13472_PF06839_896', 'N', 41, 'T'),
 ('Q13472_PF06839_896', 'N', 41, 'V'),
 ('Q13472_PF06839_896', 'N', 41, 'W'),
 ('Q13472_PF06839_896', 'N', 41, 'Y'),
 ('Q13472_PF06839_896', 'P', 15, 'A'),
 ('Q13472_PF06839_896', 'P', 15, 'C'),
 ('Q13472_PF06839_896', 'P', 15, 'D'),
 ('Q13472_PF06839_896', 'P', 15, 'E'),
 ('Q13472_PF06839_896', 'P', 15, 'F'),
 ('Q13472_PF06839_896', 'P', 15, 'G'),
 ('Q13472_PF06839_896', 'P', 15, 'H'),
 ('Q13472_PF06839_896', 'P', 15, 'I'),
 ('Q13472_PF06839_896', 'P', 15, 'K'),
 ('Q13472_PF06839_896', 'P', 15, 'L'),
 ('Q13472_PF06839_896', 'P', 15, 'M'),
 ('Q13472_PF06839_896', 'P', 15, 'N'),
 ('Q13472_PF06839_896', 'P', 15, 'Q'),
 ('Q13472_PF06839_896', 'P', 15, 'R'),
 ('Q13472_PF06839_896', 'P', 15, 'S'),
 ('Q13472_PF06839_896', 'P', 15, 'T'),
 ('Q13472_PF06839_896', 'P', 15, 'V'),
 ('Q13472_PF06839_896', 'P', 15, 'W'),
 ('Q13472_PF06839_896', 'P', 15, 'Y'),
 ('Q13472_PF06839_896', 'P', 27, 'A'),
 ('Q13472_PF06839_896', 'P', 27, 'C'),
 ('Q13472_PF06839_896', 'P', 27, 'D'),
 ('Q13472_PF06839_896', 'P', 27, 'E'),
 ('Q13472_PF06839_896', 'P', 27, 'F'),
 ('Q13472_PF06839_896', 'P', 27, 'G'),
 ('Q13472_PF06839_896', 'P', 27, 'H'),
 ('Q13472_PF06839_896', 'P', 27, 'I'),
 ('Q13472_PF06839_896', 'P', 27, 'K'),
 ('Q13472_PF06839_896', 'P', 27, 'L'),
 ('Q13472_PF06839_896', 'P', 27, 'M'),
 ('Q13472_PF06839_896', 'P', 27, 'N'),
 ('Q13472_PF06839_896', 'P', 27, 'Q'),
 ('Q13472_PF06839_896', 'P', 27, 'R'),
 ('Q13472_PF06839_896', 'P', 27, 'S'),
 ('Q13472_PF06839_896', 'P', 27, 'T'),
 ('Q13472_PF06839_896', 'P', 27, 'V'),
 ('Q13472_PF06839_896', 'P', 27, 'W'),
 ('Q13472_PF06839_896', 'P', 27, 'Y'),
 ('Q13472_PF06839_896', 'P', 4, 'A'),
 ('Q13472_PF06839_896', 'P', 4, 'C'),
 ('Q13472_PF06839_896', 'P', 4, 'D'),
 ('Q13472_PF06839_896', 'P', 4, 'E'),
 ('Q13472_PF06839_896', 'P', 4, 'F'),
 ('Q13472_PF06839_896', 'P', 4, 'G'),
 ('Q13472_PF06839_896', 'P', 4, 'H'),
 ('Q13472_PF06839_896', 'P', 4, 'I'),
 ('Q13472_PF06839_896', 'P', 4, 'K'),
 ('Q13472_PF06839_896', 'P', 4, 'L'),
 ('Q13472_PF06839_896', 'P', 4, 'M'),
 ('Q13472_PF06839_896', 'P', 4, 'N'),
 ('Q13472_PF06839_896', 'P', 4, 'Q'),
 ('Q13472_PF06839_896', 'P', 4, 'R'),
 ('Q13472_PF06839_896', 'P', 4, 'S'),
 ('Q13472_PF06839_896', 'P', 4, 'T'),
 ('Q13472_PF06839_896', 'P', 4, 'V'),
 ('Q13472_PF06839_896', 'P', 4, 'W'),
 ('Q13472_PF06839_896', 'P', 4, 'Y'),
 ('Q13472_PF06839_896', 'Q', 11, 'A'),
 ('Q13472_PF06839_896', 'Q', 11, 'C'),
 ('Q13472_PF06839_896', 'Q', 11, 'D'),
 ('Q13472_PF06839_896', 'Q', 11, 'E'),
 ('Q13472_PF06839_896', 'Q', 11, 'F'),
 ('Q13472_PF06839_896', 'Q', 11, 'G'),
 ('Q13472_PF06839_896', 'Q', 11, 'H'),
 ('Q13472_PF06839_896', 'Q', 11, 'I'),
 ('Q13472_PF06839_896', 'Q', 11, 'K'),
 ('Q13472_PF06839_896', 'Q', 11, 'L'),
 ('Q13472_PF06839_896', 'Q', 11, 'M'),
 ('Q13472_PF06839_896', 'Q', 11, 'N'),
 ('Q13472_PF06839_896', 'Q', 11, 'P'),
 ('Q13472_PF06839_896', 'Q', 11, 'R'),
 ('Q13472_PF06839_896', 'Q', 11, 'S'),
 ('Q13472_PF06839_896', 'Q', 11, 'T'),
 ('Q13472_PF06839_896', 'Q', 11, 'V'),
 ('Q13472_PF06839_896', 'Q', 11, 'W'),
 ('Q13472_PF06839_896', 'Q', 11, 'Y'),
 ('Q13472_PF06839_896', 'Q', 20, 'A'),
 ('Q13472_PF06839_896', 'Q', 20, 'C'),
 ('Q13472_PF06839_896', 'Q', 20, 'D'),
 ('Q13472_PF06839_896', 'Q', 20, 'E'),
 ('Q13472_PF06839_896', 'Q', 20, 'F'),
 ('Q13472_PF06839_896', 'Q', 20, 'G'),
 ('Q13472_PF06839_896', 'Q', 20, 'H'),
 ('Q13472_PF06839_896', 'Q', 20, 'I'),
 ('Q13472_PF06839_896', 'Q', 20, 'K'),
 ('Q13472_PF06839_896', 'Q', 20, 'L'),
 ('Q13472_PF06839_896', 'Q', 20, 'M'),
 ('Q13472_PF06839_896', 'Q', 20, 'N'),
 ('Q13472_PF06839_896', 'Q', 20, 'P'),
 ('Q13472_PF06839_896', 'Q', 20, 'R'),
 ('Q13472_PF06839_896', 'Q', 20, 'S'),
 ('Q13472_PF06839_896', 'Q', 20, 'T'),
 ('Q13472_PF06839_896', 'Q', 20, 'V'),
 ('Q13472_PF06839_896', 'Q', 20, 'W'),
 ('Q13472_PF06839_896', 'Q', 20, 'Y'),
 ('Q13472_PF06839_896', 'Q', 30, 'A'),

In [12]:
import pandas as pd
df = pd.read_csv('../data/domainome1/domainome_mapped.csv', index_col=0)
df

,domain_ID,uniprot_ID,uniprot_ID_mutation,aa_seq,fitness,fitness_sigma,scaled_fitness,scaled_fitness_sigma,ESM1v_domain,RaSP,...,Organism,Gene Names (primary),Gene Names (synonym),pdb_file,wt_seq,wild_type,position,mutation,uniprot_seq,offset_up
1,A0A2R8Y422_PF00240_2,A0A2R8Y422,A0A2R8Y422_A28C,QIFVKTLMGKTITLEVELSDTIDNVKCKIQDKEGIPPDQQRLIFAG...,0.091262,0.003764,0.025738,0.052712,-9.862297,0.944872,...,Homo sapiens (Human),NaN,NaN,/home/sareeves/PSLMs/data/domainome1/alphafold...,QIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,A,27.0,C,MQIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFA...,-1.0
2,A0A2R8Y422_PF00240_2,A0A2R8Y422,A0A2R8Y422_A28D,QIFVKTLMGKTITLEVELSDTIDNVKDKIQDKEGIPPDQQRLIFAG...,0.097388,0.003962,0.111544,0.055491,-8.525545,0.344768,...,Homo sapiens (Human),NaN,NaN,/home/sareeves/PSLMs/data/domainome1/alphafold...,QIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,A,27.0,D,MQIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFA...,-1.0
3,A0A2R8Y422_PF00240_2,A0A2R8Y422,A0A2R8Y422_A28E,QIFVKTLMGKTITLEVELSDTIDNVKEKIQDKEGIPPDQQRLIFAG...,0.110153,0.007189,0.290325,0.100693,-7.011676,-0.044519,...,Homo sapiens (Human),NaN,NaN,/home/sareeves/PSLMs/data/domainome1/alphafold...,QIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,A,27.0,E,MQIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFA...,-1.0
4,A0A2R8Y422_PF00240_2,A0A2R8Y422,A0A2R8Y422_A28F,QIFVKTLMGKTITLEVELSDTIDNVKFKIQDKEGIPPDQQRLIFAG...,0.089583,0.003577,0.002225,0.050106,-10.680157,-0.423373,...,Homo sapiens (Human),NaN,NaN,/home/sareeves/PSLMs/data/domainome1/alphafold...,QIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,A,27.0,F,MQIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFA...,-1.0
5,A0A2R8Y422_PF00240_2,A0A2R8Y422,A0A2R8Y422_A28G,QIFVKTLMGKTITLEVELSDTIDNVKGKIQDKEGIPPDQQRLIFAG...,0.087045,0.003294,-0.033329,0.046134,-7.925185,0.662229,...,Homo sapiens (Human),NaN,NaN,/home/sareeves/PSLMs/data/domainome1/alphafold...,QIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAG...,A,27.0,G,MQIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFA...,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
607076,Q9Y6V0_PF05715_1058,Q9Y6V0,Q9Y6V0_W1104S,TCPLCKTELNIGSKDPPNFNTCTECKNQVCNLCGFNPTPHLTEIQE...,0.105455,0.012201,-0.029589,0.137867,-5.345161,5.397289,...,Homo sapiens (Human),PCLO,ACZ KIAA0559,NaN,NaN,NaN,NaN,NaN,NaN,NaN
607077,Q9Y6V0_PF05715_1058,Q9Y6V0,Q9Y6V0_W1104T,TCPLCKTELNIGSKDPPNFNTCTECKNQVCNLCGFNPTPHLTEIQE...,0.090854,0.015305,-0.194564,0.172938,-5.214868,4.558003,...,Homo sapiens (Human),PCLO,ACZ KIAA0559,NaN,NaN,NaN,NaN,NaN,NaN,NaN
607078,Q9Y6V0_PF05715_1058,Q9Y6V0,Q9Y6V0_W1104V,TCPLCKTELNIGSKDPPNFNTCTECKNQVCNLCGFNPTPHLTEIQE...,0.115816,0.010449,0.087485,0.118070,-4.870904,3.148088,...,Homo sapiens (Human),PCLO,ACZ KIAA0559,NaN,NaN,NaN,NaN,NaN,NaN,NaN
607079,Q9Y6V0_PF05715_1058,Q9Y6V0,Q9Y6V0_W1104Y,TCPLCKTELNIGSKDPPNFNTCTECKNQVCNLCGFNPTPHLTEIQE...,0.064475,0.022245,-0.492635,0.251357,-4.390252,1.411740,...,Homo sapiens (Human),PCLO,ACZ KIAA0559,NaN,NaN,NaN,NaN,NaN,NaN,NaN
607080,Q9Y6V0_PF05715_1058,Q9Y6V0,Q9Y6V0_NANANA,TCPLCKTELNIGSKDPPNFNTCTECKNQVCNLCGFNPTPHLTEIQE...,0.108073,0.004972,0.000000,0.056184,NaN,0.065591,...,Homo sapiens (Human),PCLO,ACZ KIAA0559,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
df_filtered = df.dropna(subset=['position', 'pdb_file', 'scaled_fitness'])
df_filtered = df_filtered.loc[~df_filtered['uniprot_ID_mutation'].str.contains('NANANA')]
df_filtered['position'] = df_filtered['position'].astype(int)
df_filtered['code'] = df_filtered['domain_ID']
df_filtered['chain'] = 'A'
df_filtered['mut_type'] = df_filtered['wild_type'] + df_filtered['position'].astype(str) + df_filtered['mutation']
df_filtered['ddG_ML'] = df_filtered['scaled_fitness']
df_filtered = df_filtered[['uniprot_ID_mutation', 'code', 'chain', 'mut_type', 'wild_type', 'position', 'mutation', 'aa_seq', 'pdb_file', 'ddG_ML']]
df_filtered.to_csv('../data/domainome1/domainome_mapped_filtered.csv')
df_filtered

,uniprot_ID_mutation,code,chain,mut_type,wild_type,position,mutation,aa_seq,pdb_file,ddG_ML
1,A0A2R8Y422_A28C,A0A2R8Y422_PF00240_2,A,A27C,A,27,C,QIFVKTLMGKTITLEVELSDTIDNVKCKIQDKEGIPPDQQRLIFAG...,/home/sareeves/PSLMs/data/domainome1/alphafold...,0.025738
2,A0A2R8Y422_A28D,A0A2R8Y422_PF00240_2,A,A27D,A,27,D,QIFVKTLMGKTITLEVELSDTIDNVKDKIQDKEGIPPDQQRLIFAG...,/home/sareeves/PSLMs/data/domainome1/alphafold...,0.111544
3,A0A2R8Y422_A28E,A0A2R8Y422_PF00240_2,A,A27E,A,27,E,QIFVKTLMGKTITLEVELSDTIDNVKEKIQDKEGIPPDQQRLIFAG...,/home/sareeves/PSLMs/data/domainome1/alphafold...,0.290325
4,A0A2R8Y422_A28F,A0A2R8Y422_PF00240_2,A,A27F,A,27,F,QIFVKTLMGKTITLEVELSDTIDNVKFKIQDKEGIPPDQQRLIFAG...,/home/sareeves/PSLMs/data/domainome1/alphafold...,0.002225
5,A0A2R8Y422_A28G,A0A2R8Y422_PF00240_2,A,A27G,A,27,G,QIFVKTLMGKTITLEVELSDTIDNVKGKIQDKEGIPPDQQRLIFAG...,/home/sareeves/PSLMs/data/domainome1/alphafold...,-0.033329
...,...,...,...,...,...,...,...,...,...,...
605839,Q9Y6N9_V289R,Q9Y6N9_PF00595_207,A,V83R,V,83,R,NKEKKVFISLVGSRGLGCSISSGPIQKPGIFISHVKPGSLSAEVGL...,/home/sareeves/PSLMs/data/domainome1/alphafold...,0.040825
605840,Q9Y6N9_V289S,Q9Y6N9_PF00595_207,A,V83S,V,83,S,NKEKKVFISLVGSRGLGCSISSGPIQKPGIFISHVKPGSLSAEVGL...,/home/sareeves/PSLMs/data/domainome1/alphafold...,-0.228931
605841,Q9Y6N9_V289T,Q9Y6N9_PF00595_207,A,V83T,V,83,T,NKEKKVFISLVGSRGLGCSISSGPIQKPGIFISHVKPGSLSAEVGL...,/home/sareeves/PSLMs/data/domainome1/alphafold...,-0.353383
605842,Q9Y6N9_V289W,Q9Y6N9_PF00595_207,A,V83W,V,83,W,NKEKKVFISLVGSRGLGCSISSGPIQKPGIFISHVKPGSLSAEVGL...,/home/sareeves/PSLMs/data/domainome1/alphafold...,-0.185128
605843,Q9Y6N9_V289Y,Q9Y6N9_PF00595_207,A,V83Y,V,83,Y,NKEKKVFISLVGSRGLGCSISSGPIQKPGIFISHVKPGSLSAEVGL...,/home/sareeves/PSLMs/data/domainome1/alphafold...,-0.238159

In [4]:
with open('../data/domainome1/domainome_seq.fasta', 'w') as f:
    for (domain, wt_seq), group in df.groupby(['domain_ID', 'wt_seq']):
        print(domain, wt_seq)
        f.write(f'>{domain}\n')
        f.write(f'{wt_seq}\n')

A0A2R8Y422_PF00240_2 QIFVKTLMGKTITLEVELSDTIDNVKAKIQDKEGIPPDQQRLIFAGKQLEDGRTLSDYNIQKESTLHLVL
A0PJY2_PF00096_289 VCKVCGKGFRQASTLCRHKIIH
A1X283_PF00018_155 EQYVVVANYQKQESSEISLSVGQVVDIIEKNESGWWFVSTAEEQGWVPATCLEGQ
A1X283_PF00018_222 EEEKYTVIYPYTARDQDEMNLERGAVVEVIQKNLEGWWKIRYQGKEGWAPASYLKKNSG
A2RRE5_PF01846_267 SQQIATAKDKYEWLVSRIVKNHNENWLSVSRKMQASPEYQDYVYLEGTQKAKKLFLQHIHRLK
A6NK59_PF07525_532 RSLKHLCRLKIRKCMGRLHLRCPVFMSFLPLPNRLKAYVLY
O00308_PF00397_440 MIQEPALPPGWEMKYTSEGVRYFVDHNTRTTTFKDPRPGFESGTKQGSPGAYDR
O00330_PF02817_181 RFRLSPAARNILEKHSLDASQGTATGPRGIFTKEDALKLVQLKQTGK
O14529_PF02376_1036 GIQEIVAMSPELDTYSITKRVKEVLTDNNLGQRLFGESILGLTQGSVSDLLSRPKPWHKLSLKGREPFVRMQLWLNDPHNVEKLRDMKK
O14529_PF02376_895 EVDTLELTRQVKEKLAKNGICQRIFGEKVLGLSQGSVSDMLSRPKPWSKLTQKGREPFIRMQLWLSDQL
O14640_PF00595_246 SLNIVTVTLNMERHHFLGISIVGQSNDRGDGGIYIGSIMKGGAVAADGRIEPGDMLLQVNDVNFENMSNDDAVRVLREIVSQTGPISLTVAKC
O14640_PF00778_4 TKIIYHMDEEETPYLVKLPVAPERVTLADFKNVLSNRPVHAYKFFFKSMDQDFGVVKEEIFDDNAKLPCFNGRVVSWL
O14776_PF01846_645 EAEIKAARERAIVPLEARMKQFKDMLLERGVSAFSTWEKELHKIVFDPRYLLLNPKERKQVFDQYVKTR
O14776_PF01846_727 QAKEDFKKMMEEAKFNPRATFSEFAAKHAKDSRFKAIEKMKDREALFNEF
O14776_PF01846_793 EKIKSDFFELLSNHHLDSQSRWSKVKDKVESDPRYKAVDSSSMREDLFKQYIEKIAKNLDSE
O14776_PF01846_897 EEAIQNFKALLSDMVRSSDVSWSDTRRTLRKDHRWESGSLLEREEKEKLFNEHIEALTK
O14776_PF01846_955 KKKREHFRQLLDETSAITLTSTWKEVKKIIKEDPRCIKFSSSDRKKQREFEEYIRD
O14813_PF00046_92 RIRTTFTSAQLKELERVFAETHYPDIYTREELALKIDLTEARVQVWFQNRRAKFRK
O14901_PF00096_395 VCSFPGCRKTYFKSSHLKAHLRTH
O14936_PF00595_488 VRLVQFQKNTDEPMGITLKMNELNHCIVARIMHGGMIHRQGTLHVGDEIREINGISVANQTVEQLQKMLREMRGSITFKIVP
O15151_PF00641_299 TSEDEWQCTECKKFNSPSKRYCFRCWALRKD
O15259_PF00018_152 STGEEYIAVGDFTAQQVGDLTFKKGEILLVIEKKPDGWWIAKDAKGNEGLVPRTYLEPYS
O15265_PF08313_334 KRLSEREFDPDIHCGVIDLDTKKPCTRSLTCKTHSLTQRRAVQGRRKRFDVLLAEHKNKTR
O15266_PF00046_119 RSRTNFTLEQLNELERLFDETHYPDAFMREELSQRLGLSEARVQVWFQNRRAKCRK
O15344_PF00643_172 GLMCLEHEDEKVNMYCVTDDQLICALCKLVGRHRDHQVAALSE
O15350_PF07647_487 YHADPSLVSFLTGLGCPNCIEYFTSQGLQSIYHLQNLTIEDLGALKIPEQYRMTIWRGLQDLK
O15405_PF00505_256 QKPVSAYALFFRDTQAAIKGQNPNATFGEVSKIVASMWDSLGEEQKQVYKRKTEAAKKEYLKALAAYR
O15541_PF00642_198 QPDICKDYKETGFCGFGDSCKFLHD
O43167_PF00096_351 TCTVCSKALTTKHSLLEHMSLH
O43167_PF00096_435 TCEICGKSFTAKSSLQTHIRIH
O43186_PF00046_41 RERTTFTRSQLEELEALFAKTQYPDVYAREEVALKINLPESRVQVWFKNRRAKCRQ
O43295_PF00018_745 EQIEAIAKFDYMGRSPRELSFKKGASLLLYHRASEDWWEGRHNGVDGLIPHQYIVVQD
O43353_PF00619_438 QWIQSKREDIVNQMTEACLNQSLDALLSRDLIMKEDYELVSTKPTRTSKVRQLLDTTDIQGEEFAKVIVQKLKDNKQMGLQ
O43374_PF00779_682 YHPGVFRGDKWSCCHQKEKTGQGCDKTR
O43395_PF01480_10 ELKPWIEKTVKRVLGFSEPTVVTAALNCVGKGMDKKKAADHLKPFLDDSTLRFVDKLFEAVEEGRSSR
O43586_PF00018_361 AQEYRALYDYTAQNPDELDLSAGDILEVILEGEDGWWTVERNGQRGFVPGSYLEKL
O60293_PF10650_1186 CRFDLTGTCNDDDCQWQHI
O60341_PF04433_186 DRMTSQEAACFPDIISGPQQTQKVFLFIRNRTLQLWLDNPKIQLTFEATLQQLEAPYNSDTVLVHRVHSYLERHGLINF
O60481_PF00096_389 ICKVCDKSYTHPSSLRKHMKVH
O60885_PF17035_607 CKPMSYEEKRQLSLDINKLPGEKLGRVVHIIQSREPSLKNSNPDEIEIDFETLKPSTLRELERYVTS
O75112_PF00595_1 MSYSVTLTGPGPWGFRLQGGKDFNMPLTISRITPGSKAAQSQLSQGDLVVAIDGVNTDTMTHLEAQNKIKSASYNLSLTLQKS
O75360_PF00046_71 RHRTTFSPVQLEQLESAFGRNQYPDIWARESLARDTGLSEARIQVWFQNRRAKQRK
O75366_PF02209_785 LSEQDFVSVFGITRGQFAALPGWKQLQMKKEKGLF
O75369_PF00630_1423 KVKIAGPGLGSGVRARVLQSFTVDSSKAGLAPLEVRVLGPRGLVEPVNVVDNGDGTHTVTYTPSQEGPYMVSVKYADEEIPRSPFKVKVL
O75369_PF00630_2109 ATVGSICDLNLKIPEINSSDMSAHVTSPSGRVTEAEIVPMGKNSHCVRFVPQEMGVHTVSVKYRGQHVTGSPFQFTVG
O75369_PF00630_2289 RLTVMSLQESGLKVNQPASFAIRLNGAKGKIDAKVHSPSGAVEECHVSELEPDKYAVRFIPHENGVHTIDVKFNGSHVVGSPFKVRVGEP
O75382_PF00643_111 RPLSCPNHEGKTMEFYCEACETAMCGECRAGEHREHGTVLLRDV
O75400_PF00397_176 TPAEQLLSKCPWKEYKSDSGKPYYYNSQTKESRWAKPKELEDLEGYQNTIV
O75400_PF01846_395 EAKQAFKELLKEKRVPSNASWEQAMKMIINDPRYSALAKLSEKKQAFNAY
O75400_PF01846_459 KYKEAKESFQRFLENHEKMTSTTRYKKAEQMFGEMEVWNAISERDRLEIYEDVL
O75400_PF01846_670 ARYHDEKKIIKDILKDKGFVVEVNTTFEDFVAIISSTKRSTTLDAGNIKLAFNSL
O75400_PF01846_745 RKESAFKSMLKQAAPPIELDAVWEDIRERFVKEPAFEDITLESERKRIFKDFMHVLEHEC
O75478_PF04433_375 KLNEKEKELCQMVRLVPGAYLEYKSALLNECNKQGGLRLAQARALIKIDVNKTRKIYDFLIREGYI
O75534_PF00313_184 ARCQGVVCAMKEAFGFIERGDVVKEIFFHYSEFKGDLETLQPGDDVEFTIKDRNGKEVATDVRLLPQGTVI
O75534_PF00313_23 ALRETGVIEKLLTSYGFIQCSERQARLFFHCSQYNGNLQDLKVGDDVEFEVSSDRRTGKPIAVKLVKIK
O75534_PF00313_347 AREMGVIAAMRDGFGFIKCVDRDVRMFFHFSEILDGNQLHIADEVEFTVVPDMLSAQRNHAIRIKKLPKGTV
O75554_PF06220_8 QPKKFCDYCKCWIADNRPSVEFHERGKNHKENVAKR
O75808_PF00641_4 VGEWSCVRCTFLNPAGQRQCSICEAPR
O75953_PF00226_4 DYYKILGIPSGANEDEIKKAYRKMALKYHPDKNKEPNAEEKFKEIAEAYDVLSDPKKRGLYD
O75970_PF00595_1003 ESFERTINIAKGNSSLGMTVSANKDGLGMIVRSIIHGGAISRDGRIAIGDCILSINEESTISVTNAQARAMLRRHSLIGPDIKITYVP
O75970_PF00595_1860 LRTVEMKKGPTDSLGISIAGGVGSPLGDVPIFIAMMHPTGVAAQTQKLRVGDRIVTICGTSTEGMTHTQAVNLLKNASGSIEMQV
O75970_PF00595_372 ESETFDVELTKNVQGLGITIAGYIGDKKLEPSGIFVKSITKSSAVEHDGRIQIGDQIIAVDGTNLQGFTNQQAVEVLRHTGQTVLLTLMRRG
O75970_PF00595_693 MWEAGIQHIELEKGSKGLGFSILDYQDPIDPASTVIIIRSLVPGGIAEKDGRLLPGDRLMFVNDVNLENSSLEEAVEALKGAPSGTVRIGVAKPLP
O94830_PF00536_389 TLEEDLKKLQLSEFFDIFEKEKVDKEALALCTDRDLQEIGIPLGPRKKILNYFSTRKNS
O94885_PF00536_630 GRPPQPKSVEDLLDRINLKEHMPTFLFNGYEDLDTFKLLEEEDLDELNIRDPEHRAVLLTAVELLQEYDSN
O94929_PF00412_149 SHCAGCKEEIKHGQSLLALDKQWHVSCFKCQTCSVILTGEYISKDGVPYCESDYHAQF
O94929_PF00412_210 CETCDRYISGRVLEAGGKHYHPTCARCVRCHQMFTEGEEMYLTGSEVWHPICKQAAR
O94993_PF00505_338 KRPMNAFMVWARIHRPALAKANPAANNAEISVQLGLEWNKLSEEQKKPYYDEAQKIKEKHREEFPGW
O95076_PF00046_155 RNRTTFSTFQLEELEKVFQKTHYPDVYAREQLALRTDLTEARVQVWFQNRRAKWRK
O95155_PF04564_1229 PDEFRDPLMDTLMTDPVRLPSGTIMDRSIILRHLLNSPTDPFNRQTLTESMLEPVPELKEQIQAWMREKQN
O95218_PF00641_11 GDWICPDKKCGNVNFARRTSCNRCG
O95218_PF00641_9 SDGDWICPDKKCGNVNFARRTSCNRCG
O95267_PF00130_539 GFPHNFQETTYLKPTFCDNCAGFLWGVIKQGYRCKDCGMNCHKQCKDLVVFECKK
O95343_PF00046_212 CFKERTRSLLREWYLQDPYPNPSKKRELAQATGLTPTQVGNWFKNRRQRDR
O95409_PF18366_250 QCIKQELICKWIDPEQLSNPKKSCNKTFSTMHELVTHVSVEHVGGP
O95475_PF00046_134 CFKERTRHLLREWYLQDPYPNPSKKRELAQATGLTPTQVGNWFKNRRQRDR
O95718_PF00105_100 KRLCLVCGDIASGYHYGVASCEACKAFFKRTIQGNIEYSCPATNECEITKRRRKSCQACRFMKCLKVGMLKEGVRLD
O95789_PF06467_427 KLKCQHCNHLFATKPELLFYKGKMFLFCGKNCSDEYKKKN
O95789_PF06467_469 VAMCDYCKLQKIIKETVRFSGVDKPFCSEVCKFLSA
O95793_PF00035_183 KSEISQVFEIALKRNLPVNFEVARESGPPHMKNFVTKVSVGEFVGEGEGKSKKISKKNAAIAVLEEL
O95817_PF00397_11 QVASGNGDRDPLPPGWEIKIDPQTGWPFFVDHNSRTTTWNDPRVPSEGP
O95835_PF00627_98 TSEVNPQMLQDLQAAGFDEDMVIQALQKTNNRSIEAAIEFISKM
P00519_PF00018_64 NLFVALYDFVASGDNTLSITKGEKLRVLGYNHNGEWCEAQTKNGQGWVPSNYITPVN
P01053_PF00280_22 KTEWPELVGKSVEEAKKVILQDKPEAQIIVLPVGTIVTMEYRIDRVRLFVDKLDNIAQVPRVG
P02417_PF01281_1 MKVIFLKDVKGKGKKGEIKNVADGYANNFLFKQGLAIEATPANLKAL
P02549_PF00018_979 EQRVMALYDFQARSPREVTMKKGDVLTLLSSINKDWWKVEAADHQGIVPAVYVRRLAH
P02585_PF13499_1 MTDQQAEARSYLSEEMIAEFKAAFDMFDADGGGDISVKELGTVMRMLGQTPTKEELDAIIEEVDEDGSGTIDFEEFLVMMVRQ
P02633_PF01023_1 MSAKKSPEELKGIFEKYAAKEGDPNQLSKEELKLLLQTEFPSLLKGPSTLDELFEELDKNGDGEVSFEEFQVLVKKISQ
P02640_PF02209_762 KLETFPLDVLVNTAAEDLPRGVDPSRKENHLSDEDFKAVFGMTRSAFANLPLWKQQNLKKEKGLF
P02640_PF02209_792 LSDEDFKAVFGMTRSAFANLPLWKQQNLKKEKGLF
P04049_PF02196_58 IRVFLPNKQRTVVNVRNGMSLHDCLMKALKVRGLQPECCAVFRLLHEHKGKKARLDWNTDAASLIGEELQV
P04150_PF00105_419 KLCLVCSDEASGCHYGVLTCGSCKVFFKRAVEGQHNYLCAGRNDCIIDKIRRKNCPACRYRKCLQAGMNLEARKTK
P05813_PF00030_31 WKITIYDQENFQGKRMEFTSSCPNVSERSFDNVRSLKVESGAWIGYEHTSFCGQQFILERGEYPRWDAWSGSNAYHIERLMSFRPICSA
P06239_PF00018_63 DNLVIALHSYEPSHDGDLGFEKGEQLRILEQSGEWWKAQSLTTGQEGFIPFNFVAKAN
P06241_PF00018_83 GVTLFVALYDYEARTEDDLSFHKGEKFQILNSSEGDWWEARSLTTGETGYIPSNYVAPVDS
P07315_PF00030_4 ITFYEDRAFQGRSYETTTDCPNLQPYFSRCNSIRVESGCWMLYERPNYQGQQYLLRRGEYPDYQQWMGLSDSIRSC
P07315_PF00030_91 RLYEREDHKGLMMELSEDCPSIQDRFHLSEIRSLHVLEGCWVLYELPNYRGRQYLLRPQEYRRCQDWGAMDAKAGSLRRV
P07316_PF00030_1 MGKITFYEDRAFQGRSYECTTDCPNLQPYFSRCNSIRVESGCWMIYERPNYQGHQYFLRRGEYPDYQQWMGLSDSIRSCCLIPP
P07316_PF00030_87 GAYRMKIYDRDELRGQMSELTDDCISVQDRFHLTEIHSLNVLEGSWILYEMPNYRGRQYLLRPGEYRRFLDWGAPNAKVGSLRRVMD
P07320_PF00030_90 IRLYEREDYRGQMIEFTEDCSCLQDRFRFNEIHSLNVLEGSWVLYELSNYRGRQYLLMPGDYRRYQDWGATNARVGSLRRV
P07751_PF00018_968 GKELVLALYDYQEKSPREVTMKKGDILTLLNSTNKDWWKVEVNDRQGFVPAAYVKKLDP
P07814_PF00458_827 YDEVAAQGEVVRKLKAEKSPKAKINEAVECLLSLKAQYKEKTGKEYIPGQPP
P08151_PF00096_363 VCKLPGCTKRYTDPSSLRKHVKTVH
P08235_PF00105_600 SKICLVCGDEASGCHYGVVTCGSCKVFFKRAVEGQHNYLCAGRNDCIIDKIRRKNCPACRLQKCLQAGMNLGARKS
P08631_PF00018_80 DIIVVALYDYEAIHHEDLSFQKGDQMVVLEESGEWWKARSLATRKEGYIPSNYVARVD
P09086_PF00157_200 LEELEQFARTFKQRRIKLGFTQGDVGLAMGKLYGNDFSQTTISRFEALNLSFKNMCKLKPLLEKWLNDAE
P09327_PF02209_793 LSIEDFTQAFGMTPAAFSALPRWKQQNLKKEKGLF
P0A9X9_PF00313_3 GKMTGIVKWFNADKGFGFITPDDGSKDVFVHFSAIQNDGYKSLDEGQKVSFTIESGAKGPAAGNVTSL
P0CI26_PF00643_87 SSEEQMCGTHRETKKIFCEVDRSLLCLLCSSSQEHRYHRHRPIEWAA
P10070_PF00096_565 ICKIPGCTKRYTDPSSLRKHVKTVH
P10071_PF00096_608 VCKIPGCTKRYTDPSSLRKHVKTVH
P10242_PF00249_143 KKTSWTEEEDRIIYQAHKRLGNRWAEIAKLLPGRTDNAIKNHWNSTMRRKVEQEGYLQESSK
P10242_PF00249_40 KTRWTREEDEKLKKLVEQNGTDDWKVIANYLPNRTDVQCQHRWQKVL
P10275_PF00105_557 QKTCLICGDEASGCHYGALTCGSCKVFFKRAAEGKQKYLCASRNDCTIDKFRRKNCPSCRLRKCYEAGMTLGARKL
P10398_PF02196_21 VKVYLPNKQRTVVTVRDGMSVYDSLDKALKVRGLNQDCCVVYRLIKGRKTVTAWDTAIAPLDGEELIVE
P10589_PF00105_83 HIECVVCGDKSSGKHYGQFTCEGCKSFFKRSVRRNLTYTCRANRNCPIDQHHRNQCQYCRLKKCLKVGMRREAVQRG
P10826_PF00105_85 YKPCFVCQDKSSGYHYGVSACEGCKGFFRRSIQKNMIYTCHRDKNCVINKVTRNRCQYCRLQKCFEVGMSKESVRND
P11182_PF02817_171 TLATPAVRRLAMENNIKLSEVVGSGKDGRILKEDILNYLEKQTG
P11308_PF02198_117 NMTTNERRVIVPADPTLWSTDHVRQWLEWAVKEYGLPDVNILLFQNIDGKELCKMTKDDFQRLTPSYNADILLSHLHYLRE
P11844_PF00030_85 TSSHKLRLYERDDYRGLMSELTDDCACVPELFRLPEIYSLHVLEGCWVLYEMPNYRGRQYLLRPGDYRRYHDWGGADAKVGSLRRVTDL
P11961_PF02817_126 NRRVIAMPSVRKYAREKGVDIRLVQGTGKNGRVLKEDIDAFLAGGAKP
P12081_PF00458_8 EELVKLQGERVRGLKQQKASAELIEEEVAKLLKLKAQL
P12931_PF00018_87 TTFVALYDYESRTETDLSFKKGERLQIVNNTEGDWWLAHSLSTGQTGYIPSNYVAPS
P12956_PF02037_558 EYSEEELKTHISKGTLGKFTVPMLKEACRAYGLKSGLKKQELLEALTKHFQD
P13796_PF13499_13 ELREAFAKVDTDGNGYISFNELNDLFKAACLPLPGYRVREITENLMATGDLDQDGRISFDEFIKIFHGLKSTDVAKTFRKAINK
P13984_PF02270_177 RADKQHVLDMLFSAFEKHQYYNLKDLVDITKQPVVYLKEILKEIGVQNVKGIHKNTWELKPEYR
P14598_PF00018_157 ILQTYRAIANYEKTSGSEMALSTGDVVEVVEKSESGWWFCQMKAKRGWIPASFLEPLDSPDETEDP
P14653_PF00046_208 TNFTTRQLTELEKEFHFNKYLSRARRVEIAATLELNETQVKIWFQNRRMKQKK
P14859_PF00157_285 LEELEQFAKTFKQRRIKLGFTQGDVGLAMGKLYGNDFSQTTISRFEALNLSFKNMCKLKPLLEKWLNDAE
P14921_PF02198_55 GFTKEQQRLGIPKDPRQWTETHVRDWVMWAVNEFSLKGVDFQKFCMNGAALCALGKDCFLELAPDFVGDILWEHLEILQKE
P15056_PF02196_153 QKPIVRVFLPNKQRTVVPARCGVTVRDSLKKALMMRGLIPECCAVYRIQDGEKKPIGWDTDISWLTGEELHVEVLE
P15498_PF00018_592 LGLPKMEVFQEYYGLPPPPGAIGPFLRLNPGDIVELTKAEAEQNWWEGRNTSTNEIGWFPCNRVKPY
P15498_PF00018_782 KYFGTAKARYDFCARDRSELSLKEGDIIKILNKKGQQGWWRGEIYGRVGWFPANYVEEDYS
P16157_PF00531_1405 MKMAVISEHLGLSWAELARELQFSVEDINRIRVENPNSLLEQSVALLNLWVIREGQNANMENLYTALQSIDRGEIVNMLE
P16885_PF00018_772 RTVKALYDYKAKRSDELSFCRGALIHNVSKEPGGWWKGDYGTRIQQYFPSNYVEDI
P16989_PF00313_84 KKVLATKVLGTVKWFNVRNGYGFINRNDTKEDVFVHQTAIKKNNPRKYLRSVGDGETVEFDVVEGEKGAEAANVTGPDGVPVEGSR
P17480_PF00505_408 KRPVSAMFIFSEEKRRQLQEERPELSESELTRLLARMWNDLSEKKKAKYKAREAALKAQSER
P19793_PF00105_132 KHICAICGDRSSGKHYGVYSCEGCKGFFKRTVRKDLTYTCRDNKDCLIDKRQRNRCQYCRYQKCLAMGMKREAVQEE
P19873_PF00280_1 SSCPGKSSWPHLVGVGGSVAKAIIERQNPNVKAVILEEGTPVTKDFRCNRVRIWVNKRGLVVSPPRIG
P19878_PF00018_241 EGEAHRVLFGFVPETKEELQVMPGNIVFVLKKGNDNWATVMFNGQKGLVPCNYLEPVELR
P19878_PF00018_456 LKKGSQVEALFSYEATQPEDLEFQEGDIILVLSKVNEEWLEGECKGKVGIFPKVFVEDC
P19878_PF00564_353 TLKVHYKYTVVMKTQPGLPYSQVRDMVSKKLELRLEHTKLSYRPRDSNELVPLSEDSMKDAWGQVKNYCLTLWCE
P20264_PF00046_408 KKRTSIEVSVKGALESHFLKCPKPSAQEITNLADSLQLEKEVVRVWFCNRRQKEKR
P20264_PF00157_320 DDLEQFAKQFKQRRIKLGFTQADVGLALGTLYGNVFSQTTICRFEALQLSFKNMCKLKPLLNKWLEEAD
P20265_PF00046_356 KKRTSIEVSVKGALESHFLKCPKPSAQEITSLADSLQLEKEVVRVWFCNRRQKEKR
P20265_PF00157_262 EDTPTSDDLEQFAKQFKQRRIKLGFTQADVGLALGTLYGNVFSQTTICRFEALQLSFKNMCKLKPLLNKWLEEADSS
P20936_PF00018_281 RRRVRAILPYTKVPDTDEISFLKGDMFIVHNELEDGWMWVTNLRTDEQGLIVEDLVEEVGR
P22492_PF00538_44 VSKLITEALSVSQERVGMSLVALKKALAAAGYDVEKNNSRIKLSLKSLVNKGILVQTRGTGASGSFKLS
P22681_PF00627_854 SPQLSSEIENLMSQGYSYQDIQKALVIAQNNIEMAKNILREFVSIS
P22914_PF00030_96 IQIFEKGDFSGQMYETTEDCPSIMEQFHMREIHSCKVLEGVWIFYELPNYRGRQYLLDKKEYRKPIDWGAASPAVQSFRRI
P23759_PF00046_219 RSRTTFTAEQLEELEKAFERTHYPDIYTREELAQRTKLTEARVQVWFSNRRARWRK
P25490_PF00096_384 VCPFDGCNKKFAQSTNLKSHILTH
P25685_PF00226_4 DYYQTLGLARGASDEEIKRAYRRQALRYHPDKNKEPGAEEKFKEIAEAYDVLSDPRKREIFD
P26367_PF00046_213 NRTSFTQEQIEALEKEFERTHYPDVFARERLAAKIDLPEARIQVWFSNRRAKWRR
P26651_PF00642_105 KTELCRTFSESGRCRYGAKCQFAHG
P28069_PF00157_130 RELEKFANEFKVRRIKLGYTQTNVGEALAAVHGSEFSQTTICRFENLQLSFKNACKLKAILSKWLEEAE
P28360_PF00046_174 KPRTPFTTAQLLALERKFRQKQYLSIAERAEFSSSLSLTETQVKIWFQNRRAKAKR
P32081_PF00313_1 MLEGKVKWFNSEKGFGFIEVEGQDDVFVHFSAIQGEGFKTLEEGQAVSFEIVEGNRGPQAANVTKEA
P32243_PF00046_40 RERTTFTRAQLDVLEALFAKTRYPDIFMREEVALKINLPESRVQVWFKNRRAKCRQ
P35251_PF00533_405 NCLEGLIFVITGVLESIERDEAKSLIERYGGKVTGNVSKKTNYLVMGRDSGQSKSDKAAALGTKIIDEDGLLNLI
P35548_PF00046_144 KPRTPFTTSQLLALERKFRQKQYLSIAERAEFSSSLNLTETQVKIWFQNRRAKAKR
P35711_PF00505_557 KRPMNAFMVWAKDERRKILQAFPDMHNSNISKILGSRWKAMTNLEKQPYYEEQARLSKQHLEKYPDYK
P35712_PF00505_622 KRPMNAFMVWAKDERRKILQAFPDMHNSNISKILGSRWKSMSNQEKQPYYEEQARLSKIHLEKYPNYK
P35713_PF00505_87 RPMNAFMVWAKDERKRLAQQNPDLHNAVLSKMLGKAWKELNAAEKRPFVEEAERLRVQHLRDHPNYK
P35716_PF00505_50 KRPMNAFMVWSKIERRKIMEQSPDMHNAEISKRLGKRWKMLKDSEKIPFIREAERLRLKHMADYPDYK
P36075_PF02845_9 HESKLSILMDMFPAISKSKLQVHLLENNNDLDLTIGLLL
P37275_PF00096_933 ECGICKKAFKHKHHLIEHMRLH
P39880_PF00046_1246 KPRVVLAPEEKEALKRAYQQKPYPSPKTIEDLATQLNLKTSTVINWFHNYRSRIRR
P39880_PF02376_548 GEEMDTAEIARQVKEQLIKHNIGQRIFGHYVLGLSQGSVSEILARPKPWNKLTVRGKEPFHKMKQFLSDEQNILALRSIQGR
P39880_PF02376_941 QEVDTIELTRQVKEKLAKNGICQRIFGEKVLGLSQGSVSDMLSRPKPWSKLTQKGREPFIRMQLWLNG
P39940_PF00397_324 GGTTSGLGELPSGWEQRFTPEGRAYFVDHNTRTTTWVDPRRQQ
P40040_PF02037_1 MADYSSLTVVQLKDLLTKRNLSVGGLKNELVQRLIKDDEESKGESEVSP
P41002_PF00646_28 RNLTILSLPEDVLFHILKWLSVEDILAVRAVHSQLKDLVDNHASVWACASFQE
P41016_PF00313_1 MQRGKVKWFNNEKGYGFIEVEGGSDVFVHFTAIQGEGFKTLEEGQEVSFEIVQGNRGPQAANVVKL
P41225_PF00505_140 KRPMNAFMVWSRGQRRKMALENPKMHNSEISKRLGADWKLLTDAEKRPFIDEAKRLRAVHMKEYPDYK
P41229_PF00628_319 AQFIESYVCRMCSRGDEDDKLLLCDGCDDNYHIFCLLPPLPEIPKGVWRCPKCVM
P42766_PF00831_9 LRGKKKEELLKQLDDLKVELSQLRVAKVTGGAASKLSKIRVVRKSIARVLTVINQ
P43320_PF00030_106 EHKIILYENPNFTGKKMEIIDDDVPSFHAHGYQEKVSSVRVQSGTWVGYQYPGYRGLQYLLEKGDYKDSSDFGAPHPQVQSVRR
P43354_PF00105_260 EGLCAVCGDNAACQHYGVRTCEGCKGFFKRTVQKNAKYVCLANKNCPVDKRRRNRCQYCRFQKCLAVGMVKEVVRTD
P45973_PF00385_21 VVEKVLDRRVVKGQVEYLLKWKGFSEEHNTWEPEKNLDCPELISEFMKK
P46934_PF00397_836 EIEQGFLPKGWEVRHAPNGRPFFIDHNTKTTTWEDPRLKIPAHLRG
P46937_PF00397_162 QSSFEIPDDVPLPAGWEMAKTSSGQRYFLNHIDQTTTWQDPRKAMLSQMN
P46937_PF00397_165 FEIPDDVPLPAGWEMAKTSSGQRYFLNHIDQTTTWQDPRKAMLSQM
P46937_PF00397_226 NSASGPLPDGWEQAMTQDGEIYYINHKNKTTSWLDPRLDPRFAMNQR
P47974_PF00642_193 KTELCRTFHTIGFCPYGPRCHFIH
P48431_PF00505_42 KRPMNAFMVWSRGQRRKMAQENPKMHNSEISKRLGAEWKLLSETEKRPFIDEAKRLRALHMKEHPDYK
P49335_PF00046_280 KKRTSIEVSVKGVLETHFLKCPKPAAQEISSLADSLQLEKEVVRVWFCNRRQKEKR
P50539_PF00010_70 STHNELEKNRRAHLRLCLERLKVLIPLGPDCTRHTTLGLLNKAKAHIKKLE
P51451_PF00018_59 DKHFVVALYDYTAMNDRDLQMLKGEKLQVLKGTGDWWLARSLVTGREGYVPSNFVARVE
P51508_PF00096_331 ICTKCGKAFIQNSELIMHEKTH
P51508_PF00096_555 VCADCGRAFIQKSELITHQRIH
P51532_PF07533_612 MSDLPVKVIHVESGKILTGTDAPKAGQLEAWLEMNPGYEVAPR
P51608_PF01429_91 RGPMYDDPTLPEGWTRKLKQRKSGRSAGKYDVYLINPQGKAFRSKVELIAYFEKVGDTSLDPNDFDFTVTGR
P51687_PF00173_87 KEEVSSHTSPETGIWVTLGSEVFDVTEFVDLHPGGPSKLMLAAGGPLEPFWALYAVHNQSHVRELLAQYKIGEL
P53673_PF00030_14 MVVWDEDGFQGRRHEFTAECPSVLELGFETVRSLKVLSGAWVGFEHAGFQGQQYILERGEYPSWDAWGGNTAYPAERLTSFRP
P53674_PF00030_57 GNYRLVVFELENFQGRRAEFSGECSNLADRGFDRVRSIIVSAGPWVAFEQSNFRGEMFILEKGEYPRWNTWSSSYRSDRLMSFRPIK
P53804_PF13639_1957 CEICHEVFKSKNVRVLKCGHKYHKGCFKQWLKGQSACPACQ
P54277_PF00505_572 KKPMSASALFVQDHRPQFLIENPKTSLEDATLQIEELWKTLSEEEKLKYEEKATKDLERYNSQMKR
P54727_PF00627_186 TGQSYENMVTEIMSMGYEREQVIAALRASFNNPDRAVEYLLMGIP
P54727_PF00627_361 QVTPQEKEAIERLKALGFPEGLVIQAYFACEKNENLAANFLLQQN
P54821_PF00046_96 RNRTTFNSSQLQALERVFERTHYPDAFVREDLARRVNLTEARVQVWFQNRRAKFRR
P55072_PF02359_26 LIVDEAINEDNSVVSLSQPKMDELQLFRGDTVLLKGKKRREAVCIVLSDDTCSDEKIRMNRVVRNNLRVRLGDVISIQPCP
P55265_PF02295_136 YQDQEQRILKFLEELGEGKATTAHDLSGKLGTPKKEINRVLYSLAKKGKLQKEAGTPPLWKIAVS
P55265_PF02295_296 MAEIKEKICDYLFNVSDSSALNLAKNIGLTKARDINAVLIDMERQGDVYRQGTTPPIWHLTDK
P55895_PF13341_415 YWITCCPTCDVDINTWVPFYSTELNKPAMIYCSHGDGHWVHAQCMDLAERTLIHLSAGSNKYYCNEHVEIARALHTP
P56915_PF00046_162 RHRTIFTDEQLEALENLFQETKYPDVGTREQLARKVHLREEKVEVWFKNRRAKWRR
P57071_PF00096_1085 ACEQCGKSFARKDMLKEHMRVH
P57073_PF00505_103 KRPMNAFMVWAQAARRKLADQYPHLHNAELSKTLGKLWRLLSESEKRPFVEEAERLRVQHKKDHPDYK
P60002_PF05129_3 RRKSKRKPPPKKKMTGTLETQFTCPFCNHEKSCDVKMDRARNTGVISCTVCLEEFQTPITYLSEPVDVYSDWIDACE
P60321_PF05741_63 CNFCKHNGESRHVYSSHQLKTPDGVVVCPILRHYVCPVCGATGDQAHTLKYCP
P61024_PF01111_1 MSHKQIYYSDKYDDEEFEYRHVMLPKDIAKLVPKTHLMSESEWRNLGVQQSQGWVHYMIHEPEPHILLFRRPLPKKPKK
P61086_PF00627_158 SSPEYTKKIENLCAMGFDRNAVIVALSSKSWDVETATELLLSN
P61960_PF03671_4 VSFKITLTSDPRLPYKVLSVPESTPFTAVLKFAAEEFKVPAATSAIITNDGIGINPAQTAGNVFLKHGSELRII
P61978_PF00013_385 GPIITTQVTIPKDLAGSIIGKGGQRIKQIRHESGASIKIDEPLEGSEDRIITITGTQDQIQNAQYLLQNSVKQY
P62993_PF00018_159 TYVQALFDFDPQEDGELGFRRGDFIHVMDNSDPNWWKGACHGQTGMFPRNYVTPVN
P67809_PF00313_52 KKVIATKVLGTVKWFNVRNGYGFINRNDTKEDVFVHQTAIKKNNPRKYLRSVGDGETVEFDVVEGEKGAEAANVTGPGGVPVQGSKYAADR
P78352_PF00595_157 KVMEIKLIKGPKGLGFSIAGGVGNQHIPGDNSIYVTKIIEGGAAHKDGRLQIGDKILAVNSVGLEDVMHEDAVAALKNTYDVVYLKVAKP
P78352_PF00595_309 REPRRIVIHRGSTGLGFNIVGGEDGEGIFISFILAGGPADLSGELRKGDQILSVNGVDLRNASHEQAAIALKNAGQTVTIIAQYKPEE
P78352_PF00595_60 EMEYEEITLERGNSGLGFSIAGGTDNPHIGDDPSIFITKIIPGGAAAQDGRLRVNDSILFVNEVDVREVTHSAAVEALKEAGSIVRLYVMRRKP
P78424_PF00046_609 KRRTSFTPQALEILNAHFEKNTHPSGQEMTEIAEKLNYDREVVRVWFCNKRQALK
P78545_PF02198_50 SLEGTEKASWLGEQPQFWSKTQVLDWISYQVEKNKYDASAIDFSRCDMDGATLCNCALEELRLVFGPLGDQLHAQLRDLTSS
P78563_PF00035_80 KNALMQLNEIKPGLQYTLLSQTGPVHAPLFVMSVEVNGQVFEGSGPTKKKAKLHAAEKALR
P82979_PF02037_3 TETVELHKLKLAELKQECLARGLETKGIKQDLIHRLQAYLEEHAE
P98175_PF00641_214 NEDWLCNKCGVQNFKRREKCFKCGVPKS
P98175_PF00641_216 DWLCNKCGVQNFKRREKCFKCGVPKS
Q00839_PF02037_6 VNVKKLKVSELKEELKKRRLSDKGLKAELMERLQAALDDEE
Q00987_PF00641_299 LADYWKCTSCNEMNPPLPSHCNRCWALRE
Q01543_PF02198_116 NMTTNERRVIVPADPTLWTQEHVRQWLEWAIKEYSLMEIDTSFFQNMDGKELCKMNKEDFLRATTLYNTEVLLSHLSYLRES
Q01826_PF02376_371 VSSEIYQWVRDELKRAGISQAVFARVAFNRTQGLLSEILRKEEDPKTASQSLLVNLRAMQNFLQLPEAERDRIYQ
Q01826_PF02376_494 INASIYDEIQQEMKRAKVSQALFAKVAATKSQGWLCELLRWKEDPSPENRTLWENLSMIRRFLSLPQPERDAIY
Q01826_PF16557_178 DLPPEQWSHTTVRNALKDLLKDMNQSSLAKECPLSQSMISSIVNSTYYANVSAAKCQEFGRWYKHFKKTK
Q01851_PF00157_266 RELEAFAERFKQRRIKLGVTQADVGSALANLKIPGVGSLSQSTICRFESLTLSHNNMIALKPILQAWLEEAEGAQREKMNKP
Q01860_PF00157_134 EESQDIKALQKELEQFAKLLKQKRITLGYTQADVGLTLGVLFGKVFSQTTICRFEALQLSFKNMCKLRPLLQKWVEEAD
Q03052_PF00157_247 EDAPSSDDLEQFAKQFKQRRIKLGFTQADVGLALGTLYGNVFSQTTICRFEALQLSFKNMCKLKPLLNKWLEETDSSS
Q03181_PF00105_71 NMECRVCGDKASGFHYGVHACEGCKGFFRRTIRMKLEYEKCERSCKIQKKNRNKCQYCRFQKCLALGMSHNAIRF
Q05066_PF00505_61 KRPMNAFIVWSRDQRRKMALENPRMRNSEISKQLGYQWKMLTEAEKWPFFQEAQKLQAMHREKYPNYK
Q05086_PF16558_30 KHLIERYYHQLTEGCGNEACTNEFCASCPTFLRMDNNAAAIKALELYKINAKLCDPH
Q05195_PF00010_58 RSTHNEMEKNRRAHLRLCLEKLKGLVPLGPESSRHTTLSLLTKAKLHIKKLE
Q05655_PF00130_228 DMPHRFKVHNYMSPTFCDHCGSLLWGLVKQGLKCEDCGMNVHHKCREKVANLCGI
Q06187_PF00018_215 ELKKVVALYDYMPMNANDLQLRKGDEYFILEESNLPWWRARDKNGQEGYIPSNYVTEAE
Q06546_PF02198_172 GYRKEQERLGIPYDPIQWSTDQVLHWVVWVMKEFSMTDIDLTTLNISGRELCSLNQEDFFQRVPRGEILWSHLELLRKY
Q06787_PF00013_217 SRFHEQFIVREDLMGLAIGTHGANIQQARKVPGVTAIDLDEDTCTFHIYGEDQDAVKKARSFLEFA
Q06945_PF00505_60 KRPMNAFMVWSQIERRKIMEQSPDMHNAEISKRLGKRWKLLKDSDKIPFIREAERLRLKHMADYPDYK
Q08881_PF00018_172 EETVVIALYDYQTNDPQELALRRNEEYCLLDSSEIHWWRVQDRNGHEGYVPSSYLVEKS
Q09472_PF02172_567 IRKQWHEDITQDLRNHLVHKLVQAIFPTPDPAALKDRRMENLVAYARKVEGDMYESANNRAEYYHLLAEKIYKIQKELEEKRRT
Q12824_PF04855_181 SQPEVLVPIRLDMEIDGQKLRDAFTWNMNEKLMTPEMFSEILCDDLDLNPLTFVPAIASAIRQQIESY
Q12837_PF00157_256 RDLEAFAERFKQRRIKLGVTQADVGSALANLKIPGVGSLSQSTICRFESLTLSHNNMIALKPILQAWLEEAE
Q12873_PF00628_374 YETDHQDYCEVCQQGGEIILCDTCPRAYHLVCLDPELDRAPEGKWSCPHCEKE
Q12899_PF00643_97 QDAKLCERHREKLHYYCEDDGKLLCVMCRESREHRPHTAVLMEK
Q12929_PF00018_533 KKYAKSKYDFVARNNSELSVLKDDILEILDDRKQWWKVRNASGDSGFVPNNILDIVRP

In [ ]:
import pickle

with open('/home/sareeves/software/esm-msr/cache_domainome/cache/A1X283_PF00018_222_ddG_ML_doubles1_mutctx0_rev0_mutS0_Smasked0.pkl', 'rb') as f:
    cf = pickle.load(f)

cf